### ISSUE TITLE
The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1227] opened 2021-02-09 23:46 UTC
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1.Open your dataset somewhere 
2.  run command "mlnet regression --dataset ".....\taxi-fare-trainlarge.csv" --label-col fare_amount"

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment] 2021-04-08 23:04
@LittleLittleCloud  I think this is by design, right? If it's open in another location we can't train with it. The same thing happens in Model Builder UI.

**Comment by LittleLittleCloud** [comment] 2021-04-09 20:30
Yes, let's close it

**Closed** 2021-04-09 20:37 UTC
Labels: CLI Bug Bash
