### ISSUE TITLE
ML.NET Builder Get Started sample throw excepion when Train time longer than 60 sec

### ISSUE THREAD

**Issue by magnusseptim** [dotnet/machinelearning-modelbuilder#238] opened 2019-09-18 18:49 UTC
**System Information**
 - Model Builder Version: Latest
 - Visual Studio Version : VS 2019 Community 16.2.5

**Bug description**
Model Builder Get Started, on step :
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
using wikipedia-detox-250-line-data.tsv, when train time is longer or equal than 60 sec, 
output shows : 

_Exception occured while exploring pipelines:
must be in range [0, 0.5)
Parameter name: L2Regularization
System.ArgumentOutOfRangeException: must be in range [0, 0.5)
Parameter name: L2Regularization
   at Microsoft.ML.CLI.CodeGenerator.CodeGenerationHelper.GenerateCode()
   at Microsoft.ML.CLI.Program.<>c__DisplayClass1_0.<Main>b__0(NewCommandSettings options)
Please see the log file for more info.
Exiting ..._

Last tested algorithm visible in output is :  

_|9    SgdCalibratedBinary                    0,7317   0,8104   0,9053    0,7925       1,4          0             |_

**Steps to Reproduce**
1. Right click on project -> Add -> Machine Learning
2. Follow Get Started from :  https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro until "Train your model"
3. In "Time to train (seconds)" textbox set >= 60 
4. Wait until output shows error

**Expected behavior**
Same as you train it shorter, no errors but starting next step

**Screenshots**
![obraz](https://user-images.githubusercontent.com/37555930/65176623-6c909200-da55-11e9-93e8-a26b70eab559.png)

**Comment by LittleLittleCloud** [comment] 2019-09-19 21:47
Seems to be the ModelBuilder that still use cli... We can try if it will reproduce on the latest release version

**Comment by telmo-rodrigues** [comment] 2019-09-30 10:32
His also happens to me whenever i try to train my Sentiment Analysis module. 10s and it throws this error. This was after the last update.
`|     Trainer                              Accuracy      AUC    AUPRC  F1-score  Duration #Iteration             |
|1    AveragedPerceptronBinary               0,9974   0,9987   0,9983    0,9974       0,5          1             |
|2    SdcaLogisticRegressionBinary           0,9923   0,9981   0,9977    0,9922       0,4          2             |
|3    LightGbmBinary                         0,9901   0,9935   0,9942    0,9900       0,6          3             |
|4    SymbolicSgdLogisticRegressionBinary    0,9921   0,9989   0,9989    0,9920       0,3          4             |
|5    LinearSvmBinary                        0,9890   0,9987   0,9984    0,9888       0,3          5             |
|6    FastTreeBinary                         0,9927   0,9953   0,9959    0,9926       1,0          6             |
|7    LbfgsLogisticRegressionBinary          0,9923   0,9981   0,9977    0,9922       0,6          7             |
|8    FastForestBinary                       0,9921   0,9953   0,9958    0,9920       0,8          8             |
|9    SgdCalibratedBinary                    0,9896   0,9989   0,9987    0,9894       0,4          9             |
must be in range [0, 0.5)
Parameter name: L2Regularization`

**Comment by mindaugas-j** [comment] 2019-11-15 07:16
in case you training model from csv file - ensure there is no empty line at the end of the file.

**Comment by justinormont** [comment] 2019-11-15 17:16
Duplicate of https://github.com/dotnet/machinelearning/issues/567
Fixed by https://github.com/dotnet/machinelearning/pull/579

Please re-open if you still see this issue. It possible the sweep ranges were not propagated to the sweep ranges used by AutoML.

Side note: AutoML should be directly accessing the sweep ranges of the ML.NET components. Instead it maintains its own copy of the sweep ranges.

**Closed by justinormont** 2019-11-15 17:16 UTC

**Comment by eyvindwa** [comment] 2019-12-04 07:07
I had this exact issue, and the problem was a blank line at the end of my dataset, like @mindaugas-j pointed out - thanks!

**Comment by eyvindwa** [comment] 2019-12-04 09:27
Hmm, well, removing the blank line helped for one dataset, but not for another. Seems this problem is not fixed after all:

`Exploring multiple ML algorithms and settings to find you the best model for ML task: multiclass-classification
For further learning check: https://aka.ms/mlnet-cli
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓────────────────────────────────────────────────────────────────────────────────────────────────────Best Accuracy: 79,12%, Best Algorithm: LbfgsLogisticRegressionOva, Last Algorithm: LbfgsMaximumEntropyMulti     00:05:04
Exception occured while exploring pipelines:
must be in range [0, 0.5)───────────────────────────────────────────────────────────────────────────────────────────────
Parameter name: L2Regularization
Please see the log file for more info.
Exiting ...`

**Comment by adepierre** [comment] 2020-01-02 17:00
I just got the exact same problem. Removing the blank line at the end of the file also seems to fix it for one dataset, but then I tried with another and the problem is back.
