### ISSUE TITLE
New feature for the ML model builder.

### ISSUE THREAD

**Issue by mikehulme6498** [dotnet/machinelearning-modelbuilder#2252] opened 2022-09-21 18:53 UTC
At the minute when you evaluate your trained model it pre-populates with row one of your trained data. This is fine when you only have one or two features to change but if you have many (like I do) it is a pain typing it out to try different parameters.

It would be good if you could select rows from your data and it filled all the fields in automatically.

**Comment by beccamc** [comment] 2022-09-21 20:01
Thanks for the suggestion @mikehulme6498. How would you feel about this functionality being exposed as a code snippet that you can modify? Or is this something you want available in the UI?

**Comment by mikehulme6498** [comment] 2022-09-21 20:33
No problem, I was thinking more in the UI, so maybe a textbox where you could enter what row you want to test. 

I'm not new to C# but very new to machine learning, I think the model builder is a great tool by the way. I am enjoying playing around with it. I still have lots to learn.

**Comment by luisquintanilla** [comment] 2022-09-22 21:11
Thanks for this feedback @mikehulme6498. Closing this issue as a duplicate of #2101. Feel free to track progress on there.

**Closed by luisquintanilla** 2022-09-22 21:11 UTC
