### ISSUE TITLE
"Column to predict" not populated

### ISSUE THREAD

**Issue by JohnFurth** [dotnet/machinelearning-modelbuilder#2685] opened 2023-05-31 19:00 UTC
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 17.16
 - Visual Studio Version (if applicable): 2022

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/data
- Clear description of the problem: "Column to predict" drop-down list is not populated with column headers after file yelp_labelled.txt is selected and preview of its data is shown. "col1" cannot be selected to proceed with the tutorial.

**To Reproduce**
1. Click on the triangle in the dropdown list box.
2. List is empty. 

**Expected behavior**
When dropdown list is displayed, it should include "col0" and "col1".

**Comment by zewditu** [comment] 2023-06-01 23:52
@JohnFurth ,Sorry for hitting this issue, this is a known issue, and we are looking into it, for the time being, save and reopen your mbconfig file.

**Comment by luisquintanilla** [comment] 2023-06-07 20:38
Closing as a dupe of #2672. Check that issue for progress.

**Closed by luisquintanilla** 2023-06-07 20:38 UTC
Labels: GS Tutorial
