### ISSUE TITLE
Invalid files should reset columns to predict

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#55] opened 2019-05-21 21:19 UTC
**System Information (please complete the following information):**
 - Model Builder Version: [RC]
 - Visual Studio Version: VS 2019

**Describe the bug**
Selecting a file that isn't valid (e.g. duplicate columns or missing headers) won't reset the column to predict dropdown. There will still be values from the last valid file. Additionally, the user can still click on the next tab (Train) to start training with the invalid file.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rustd** [comment] 2019-06-03 19:16
Duplicate of #25

**Closed by rustd** 2019-06-03 19:16 UTC
