### ISSUE TITLE
Ignored column values are used for sample data, evaluate, & ModelInput code

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2115] opened 2022-05-10 21:44 UTC
**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/167726883-800dcbc4-83c1-4c60-b6ce-8706c2db5d39.png)

![image](https://user-images.githubusercontent.com/36615490/167726979-a31b8899-82b7-42f4-a25e-1282a82fb84e.png)

**Additional context**

**Comment by beccamc** [comment] 2022-11-14 22:12
@luisquintanilla Should ignored columns be excluded from the generated ModelInput class too?

**Comment by luisquintanilla** [comment] 2022-11-14 22:19
> @luisquintanilla Should ignored columns be excluded from the generated ModelInput class too? I am assuming yes

Yeah. I think that makes sense.

**Comment by beccamc** [comment] 2022-11-15 23:16
The ModelInput class is generated from a different set of data than the sample data. Its generated from the data schema. 

@LittleLittleCloud It looks like the columns being returned in the schema are never marked as hidden. IsHidden is always false for ignored columns. Code is [here](https://github.com/dotnet/machinelearning-tools/blob/bcbe5f148badb13358f4e06c97b6045d2c40bad4/src/Microsoft.ML.ModelBuilder.CodeGenerator/Utils.cs#L94). 

![image](https://user-images.githubusercontent.com/9122518/202044792-a5288f89-ea64-4332-974a-3a6c80a615e5.png)

How is this supposed to work? I assumed Ignored columns are marked as hidden.

**Comment by JakeRadMSFT** [comment] 2022-11-16 22:34
@luisquintanilla @zewditu and I dug into the code during office hours.

We should exclude Ignored columns from ModelInput and Evaluate page.

IsHidden doesn't really have anything to do with IgnoredColumns. We need to keep track of our ignored columns ourselves.

**Comment by beccamc** [comment] 2022-11-16 22:41
Great. So we should be using the schema + column settings here. Sounds good!

**Comment by LittleLittleCloud** [comment] 2022-11-17 01:45
`IsHidden` is used to indicate intermediate column when it has the same name of an output column but different type. For example:

`ConvertType("ColumnA", "ColumnA", boolean)`, which converts `ColumnA` to boolean with same name, will generate a `ColumnA` with its original type and `isHidden` to true. When generating model output class we don't want to include thus columns so we filter those column out by checking `IsHidden` flag.

> Great. So we should be using the schema + column settings here. Sounds good!
One thing I wonder is why `vender_id` is included in training data schema even after it's marked as ignored. Normally speaking once a column is marked as ignore, it should no longer be appeared in training data schema.

**Comment by beccamc** [comment] 2022-11-17 17:25
> One thing I wonder is why vender_id is included in training data schema even after it's marked as ignored. Normally speaking once a column is marked as ignore, it should no longer be appeared in training data schema.

If vendor_id isn't supposed to be in the training data schema then I shouldn't use the schema + column settings. Is it a bug that an ignored column is in the data schema?

**Comment by beccamc** [comment] 2022-11-29 17:25
@LittleLittleCloud Ping on the above. I see two options here...
1. Training data schema **shouldn't** have ignored columns and we file a bug to fix this problem 
2. Training data schema **should** have ignored columns and I use the ColumnSettings to determine feature columns. 

Based on the comments above my understanding is option 1?

**Comment by LittleLittleCloud** [comment] 2022-12-01 01:34
> @LittleLittleCloud Ping on the above. I see two options here...
> 
> 1. Training data schema **shouldn't** have ignored columns and we file a bug to fix this problem
> 2. Training data schema **should** have ignored columns and I use the ColumnSettings to determine feature columns.
> 
> Based on the comments above my understanding is option 1?

Yep option 1 should be the solution

**Comment by v-Hailishi** [comment] 2022-12-09 02:34
The bug has been fixed on the latest main build 16.14.0.2260701
![Image](https://user-images.githubusercontent.com/99375895/206610752-78199ef1-5598-4e89-a491-0644c4354225.png)

**Comment by luisquintanilla** [comment] 2022-12-13 21:51
Hi all, 

I see that the *.consumption file still has the ignored columns. Was this the intent? Not a ship blocker.

![Image](https://user-images.githubusercontent.com/46974588/207451535-e7fe20ba-717a-4bd0-a183-610183e9aef7.png)

**Comment by luisquintanilla** [comment] 2022-12-13 22:00
Reopened and moved back to validate for now.

**Comment by zewditu** [comment] 2022-12-13 22:02
@luisquintanilla I think for this round the purpose is just to hide from the UI.

**Comment by luisquintanilla** [comment] 2022-12-13 22:04
Great. Thanks. Closing. Do we have an issue that tracks the next steps for this feature?

**Comment by zewditu** [comment] 2022-12-13 22:16
@luisquintanilla  you are right even this work item it should not be in valid stage, it should be open.
It should be reopen 
@beccamc  what is its status?

**Comment by beccamc** [comment] 2022-12-14 16:18
I've opened a new issue as there is a different root cause for this. https://github.com/dotnet/machinelearning-modelbuilder/issues/2416

**Closed by beccamc** 2022-12-14 16:18 UTC
Labels: Priority:2
