### ISSUE TITLE
Changing environment reset the "Set up workspace"

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#1289] opened 2021-02-25 20:50 UTC
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. Image classification
2.Azure  Environment
3.Set op workspace
4. change environment (either  CPU or GPU)
5. Back to Azure 

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/6c482689-556f-4381-9f07-0ef7ddfcd7de)
**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._

**Comment by beccamc** [comment] 2021-02-25 20:56
This is by design. If you change the environment we overwrite your previous value.

**Comment by beccamc** [comment] 2021-02-26 19:45
@zewditu FYI this is expected. We would be breaking our model-view model pattern to fix this.  I think this is out of scope for fixing, both because it would change our design pattern and because it would break our code pattern.

**Closed** 2021-03-08 17:57 UTC
Labels: Bug Bash, Won't Fix
