### ISSUE TITLE
Seems to be an issue with the method of saving files when using VS Code on a mac with x64 version of .Net

### ISSUE THREAD

**Issue by kaylakwright** [dotnet/machinelearning-modelbuilder#2480] opened 2023-02-07 20:33 UTC
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.14.3
 - Visual Studio Version (if applicable): Visual Studio Code 1.75.0 (Universal)

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL): Consume your model
- Clear description of the problem: I was able to follow the tutorial and train the model, however when I attempted to run the program by typing "dotnet run" into the integrated terminal, I received this error: /Users/kaylawright/kw/myMLApp/SentimentModel/SentimentModel.training.cs(62,29): error CS0103: The name 'File' does not exist in the current context [/Users/kaylawright/kw/myMLApp/SentimentModel/SentimentModel.csproj]

**To Reproduce**

**Expected behavior**

I suppose I just expected that it would run like it says it will in the tutorial and display the message it displayed for the expected behavior of the console app. :-P

**Screenshots**

//model seemed to train like expected
<img width="1568" alt="Screenshot 2023-02-07 at 1 31 41 PM" src="https://user-images.githubusercontent.com/122396374/217358378-fed36b5c-92c0-46f0-8923-7da9ce3bb8a7.png">
//two examples of the file tree it generated, the code where it generated the error:
<img width="1727" alt="Screenshot 2023-02-07 at 1 26 07 PM" src="https://user-images.githubusercontent.com/122396374/217357440-0039b87b-2bdf-41fb-8e12-e601d9ddad3c.png">
<img width="1728" alt="Screenshot 2023-02-07 at 1 29 04 PM" src="https://user-images.githubusercontent.com/122396374/217357848-86e84346-4132-4fca-b4e9-1bbb965c08c8.png">

**Additional context**

I tried to create a new file (I named it File.cs) and copy the path as the parameter for File.Create, but that didn't help. Sorry that I'm so new and I'm just not quite sure how to fix this. It seems like it would be a simple fix but I'm just not quite sure yet. Very much still learning. I started learning C# (my first language) about 4 weeks ago.

**Comment by beccamc** [comment] 2023-02-08 00:21
@kaylakwright Thanks for the detailed report! File is a reference to the [System.IO.File](https://learn.microsoft.com/en-us/dotnet/api/system.io.file?view=net-7.0), which provides methods for the creation, copying, deletion, moving, and opening of files. Your file seems to be missing that reference. 

Can you give me a screenshot of `using `statements at the top of the SentimentModel.training.cs file? As a workaround, if you're just trying to predict with the model you trained, you can comment out that method.

@v-Hailishi Can you try to reproduce this using the latest CLI?

**Comment by kaylakwright** [comment] 2023-02-08 13:35
<img width="1728" alt="Screenshot 2023-02-08 at 6 35 33 AM" src="https://user-images.githubusercontent.com/122396374/217545035-36010a43-192a-4a82-a6af-9a363d65802c.png">

**Comment by kaylakwright** [comment] 2023-02-08 13:38
<img width="1728" alt="Screenshot 2023-02-08 at 6 37 14 AM" src="https://user-images.githubusercontent.com/122396374/217545670-8e4b0fc5-d4bb-4a80-89c5-531e459de4c4.png">

**Comment by kaylakwright** [comment] 2023-02-08 13:50
@beccamc 

First I tried just adding the using statement. I got this error when I typed File after System.IO.

namespace System.IO
Unnecessary using directive. [SentimentModel]csharp(CS8019)
A 'using namespace' directive can only be applied to namespaces; 'File' is a type not a namespace. Consider a 'using static' directive instead [SentimentModel]csharp(CS0138)



So then I deleted that using statement and tried commenting out the method in question, but it apparently had a reference to other methods on the SentimentModel.training.cs file. I tried commenting out the subsequent method, but then that one had a reference to two others :-P

Kayla

**Comment by beccamc** [comment] 2023-02-08 16:15
You can comment out line 62-65

**Comment by v-Hailishi** [comment] 2023-02-14 08:55
@beccamc Verified on the latest CLI 16.14.3, the bug is also repro on the Windows.
<img width="525" alt="image" src="https://user-images.githubusercontent.com/99375895/218685750-4c587d08-e130-450f-a806-da9f1a5e420b.png">

But after you add using System.IO; the error would be fixed.
![image](https://user-images.githubusercontent.com/99375895/218686564-b72ac422-64dd-43aa-b695-9017e62c14c9.png)

**Comment by beccamc** [comment] 2023-02-14 19:24
@zewditu Can you look at why the generated project is missing the `using System.IO` statement?

**Comment by beccamc** [comment] 2023-02-22 22:18
Duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2503

**Comment by beccamc** [comment] 2023-02-22 22:18
Please track in 2503

**Closed by beccamc** 2023-02-22 22:18 UTC
Labels: GS Tutorial
