### ISSUE TITLE
ML .NET "Training cancelled" message appearing immediately upon training attempt

### ISSUE THREAD

**Issue by jessewinkler** [dotnet/machinelearning-modelbuilder#833] opened 2020-06-15 15:59 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install
Operating System: windows

I was using ML.NET 4 weeks ago without any problems, but suddenly about 2 weeks ago it started giving me this "training cancelled" message immediately after clicking the "Train" or "Train again" button. I've tried making new solutions, restarting computer, disabling and re-enabling ML.NET, and both Visual Studio 2019 version 16.6.1 and 16.6.2.

"GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled"

**Visual Studio info:**
Microsoft Visual Studio Professional 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA709
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.948.25768
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.6.948.25768
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   16.6.20100.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.6.20100.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.6.20100.1
Conda support for Python projects.

Python - Django support   16.6.20100.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.6.20100.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.6.20100.1
Profiling support for Python projects.

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

**Comment by LittleLittleCloud** [comment] 2020-06-15 17:00
We need more information here,,, can I have your log for this run?
You can get it through %temp%/MLVSTools/logs

Thanks

**Comment by jessewinkler** [comment] 2020-06-15 17:02
[a70a393e-8a64-4f37-bbca-27a62f930de5.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4781763/a70a393e-8a64-4f37-bbca-27a62f930de5.txt)
[fe618926-3db0-4a09-99e5-985499f575f3.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/4781765/fe618926-3db0-4a09-99e5-985499f575f3.txt)

**Comment by LittleLittleCloud** [comment] 2020-06-15 17:11
The log from Modelbuilder look fine, the error might be from servicehub
Can I also have your servicehub log too? you can get it from %temp%/servicehub/logs.

Thanks

**Comment by jessewinkler** [comment] 2020-06-15 17:14
[2B548135-CodeLens-22068-cooit02d-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781838/2B548135-CodeLens-22068-cooit02d-1.log)
[2B548135-CreateAutoMLServiceAsync-20744-ilzndmsf-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781839/2B548135-CreateAutoMLServiceAsync-20744-ilzndmsf-1.log)
[2B548135-hubController-20832-k13oxjir-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781840/2B548135-hubController-20832-k13oxjir-1.log)
[2B548135-Microsoft.Developer.AccountManagement-15340-3c1akuvg-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781841/2B548135-Microsoft.Developer.AccountManagement-15340-3c1akuvg-1.log)
[2B548135-MicrosoftMLModelBuilderAutoML-18540-4myxbapt-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781842/2B548135-MicrosoftMLModelBuilderAutoML-18540-4myxbapt-1.log)
[2B548135-roslynLanguageServer-3852-13c3sduz-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781843/2B548135-roslynLanguageServer-3852-13c3sduz-1.log)
[2B548135-VsixServiceDiscovery-23364-hmobvhkl-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781845/2B548135-VsixServiceDiscovery-23364-hmobvhkl-1.log)
[2B548135-VsixServiceDiscovery-23364-ncwe135j-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781846/2B548135-VsixServiceDiscovery-23364-ncwe135j-1.log)
[2B548135-VsixServiceDiscovery-23364-zvte3mqn-1.log](https://github.com/dotnet/machinelearning-modelbuilder/files/4781847/2B548135-VsixServiceDiscovery-23364-zvte3mqn-1.log)

**Comment by LittleLittleCloud** [comment] 2020-06-15 17:41
Thanks!

**Comment by LittleLittleCloud** [comment] 2020-06-15 17:55
Looks like a dup of #267 

We are working on a fix(#834 ) for this issue

@jessewinkler  Can you help us test that fix when it's ready? It's a rare bug from CLR, and is quite difficult to reproduce.

Please reply to #834 if you want to try that test fix!

**Comment by Luk164** [comment] 2020-06-30 19:29
This happened to me too, when I try to run local machine learning this is the output:

`GPU Service not found. Falling back to CPU AutoML Service.`

I cancelled after it showed because I have no desire to let it run on CPU.

**Comment by rymexs** [comment] 2020-07-01 21:52
I also have this problem, trying to start training using VS 2019 v16.6.3:

**GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled**

**Comment by LittleLittleCloud** [comment] 2020-07-02 17:46
@rymexs 
looks like a dup of #267

We have a fix(#834 ) for this issue, and it will be release soon. 

Can you help us test that fix when it's ready? It's a rare bug from CLR, and is quite difficult to reproduce.

Please reply to #834 if you want to try that test fix!

**Comment by LittleLittleCloud** [comment] 2020-07-02 18:28
I'm going to close this issue because of problem solved.

**Closed by LittleLittleCloud** 2020-07-02 18:28 UTC
Labels: Customer Reported
