### ISSUE TITLE
When Image folder contain unsupported format piles of error windows displayed.

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#2306] opened 2022-10-20 22:33 UTC
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**
A single winddow

**Screenshots**
![image](https://user-images.githubusercontent.com/36615490/197071542-73f06944-6b59-4250-9bfd-ca6a94c55c3f.png)

**Additional context**

**Comment by beccamc** [comment] 2022-10-27 16:07
Duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/2284

**Closed by beccamc** 2022-10-27 16:07 UTC
Labels: Bug Bash, Priority:1
