### ISSUE TITLE
Image training data load fails with single images

### ISSUE THREAD

**Issue by patteesolomon** [dotnet/machinelearning-modelbuilder#2256] opened 2022-09-24 22:02 UTC
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**
1. Setup the scenario
2. Setup the Environment
3. Give it the Image folder index
4. It gets stuck at the data step

**Expected behavior**
This should just let me go to the next step.

**Screenshots**
![image](https://user-images.githubusercontent.com/113143898/192119776-d057b37d-9b39-4d2d-90e4-2a126747370e.png)

**Comment by beccamc** [comment] 2022-09-26 18:43
@patteesolomon Sorry you've run into this problem and thanks for reporting. 

- What version of Model Builder are you using? Can you make sure its [16.13.10](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022)? 
- How is your image folder structured? Does it have a top folder, containing subfolders of images? 
- What file format are your images? (i.e. .jpg, .png)
- Approximately how many images do you have?

**Comment by GhandiHopZX** [comment] 2022-09-26 20:23
I already downloaded the version you mentioned.
My folder is structured the way the program wanted me to 
set it up.
.pngs
How many do I really need?

**Comment by patteesolomon** [comment] 2022-09-26 20:25
I already downloaded the version you mentioned.
My folder is structured the way the program wanted me to
set it up.
.pngs
How many do I really need?

**Comment by beccamc** [comment] 2022-09-26 20:35
Can you zip your data and upload it? 

Something is going wrong in processing the data. If it were processing correctly it should show you a data preview. I asked how many images you had in case you have a large number and it was slow to process.

**Comment by patteesolomon** [comment] 2022-09-26 21:01
here you can look at my folder hierarchy..
[image.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/9649657/image.zip)

**Comment by beccamc** [comment] 2022-10-04 15:48
Sorry for the delay here. The problem is you have only one image per folder. We recommend having at least 5 images per folder. There is supposed to be an error message but it looks like that experience is broken. Sorry about that.

**Comment by luisquintanilla** [comment] 2022-10-20 22:37
Issue fixed in latest build 16.14.0.2252005

![Image](https://user-images.githubusercontent.com/46974588/197071887-0744f6dc-8379-4d8c-b454-7a72d0e6a4b6.png)

**Comment by beccamc** [comment] 2022-11-09 17:01
This fix has shipped! Please install the latest version of Model Builder [16.14.0](https://marketplace.visualstudio.com/items?itemName=MLNET.ModelBuilder2022) to see the change.

**Closed by beccamc** 2022-11-09 17:01 UTC
Labels: Reported by: Customer, Mark for close
