### ISSUE TITLE
VS 2017 Keeps crashing when I start training the data

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#40] opened 2019-05-13 16:57 UTC
Copying from here: https://github.com/dotnet/machinelearning-samples/issues/440
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/train
Operating System: windows

From the steps provided from the tutorial, I am able to load the data and the preview loads fine too.
But when I start the training, VS crashes and restarts.

I am using VS Community 2017 15.9.6 on Win7 machine. I created a .net core 2.2 console App with platform target x64.

Please let me know what am I missing here.
Thank you.

**Comment by greazer** [comment] 2019-06-18 06:24
Windows 7 could be the culprit here.

**Comment by greazer** [comment] 2019-06-18 08:21
I verified that the sentiment analysis tutorial does not crash when Training on Window 7 N Enterprise, under Visual Studio 2019.  I'm using the June build of the Model Builder extension.

It could be that it's a combination of Windows 7 AND Visual Studio **2017**.

**Comment by greazer** [comment] 2019-06-18 19:05
I was able to run Model Builder successfully on Windows 7 with Visual Studio 2017 (v 15.9.13 -- the latest).

**Comment by greazer** [comment] 2019-06-24 23:45
I have been unable to reproduce the problem, and I haven't seen an update from the customer who experienced this. So closing.

**Closed by greazer** 2019-06-24 23:45 UTC
Labels: Customer Reported, Needs Details, P0
