### ISSUE TITLE
Выполнение завершено без обученной модели

### ISSUE THREAD

**Issue by KotoRina** [dotnet/machinelearning-modelbuilder#707] opened 2020-04-27 08:14 UTC
Ошибка:
   в System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   в Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() в E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:строка 117
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() в E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:строка 134

Вариант: Классификация изображений
Набор данных: Три папки для классификации по 12 картинок в каждой

**Comment by LittleLittleCloud** [comment] 2020-04-27 17:51
Можете ли вы попытаться увеличить время тренировки?

**Comment by KotoRina** [comment] 2020-04-29 08:31
В варианте Image Classification нет выбора времени тренировки.
![image](https://user-images.githubusercontent.com/64101388/80575847-e128a780-8a0c-11ea-812a-2a5b558d9236.png)

**Comment by LittleLittleCloud** [comment] 2020-04-29 17:19
Did you see the log start with `[Source=ImageClassificationTrainer; ` before training canceled? (sorry my Russian is bad,,,, so switch back to English here)
```
|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] Downloading resnet_v2_50_299.meta from https://aka.ms/mlnet-resources/resnet_v2_50_299.meta to C:\Users\xiaoyuz\AppData\Local\Temp\MLNET\resnet_v2_50_299.meta
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 3711 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 10264576 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 20525056 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 30785536 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 41050112 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 51310592 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 61571072 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 71835648 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 82096128 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 92356608 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Downloaded 102616931 bytes out of 102616931
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Info] resnet_v2_50_299.meta: Download complete
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:01:12.1951597.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   1
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   2
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   3
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   4
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   5
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   6
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   7
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   8
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:   9
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  10
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  11
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  12
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  13
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  14
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  15
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  16
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Phase: Bottleneck Computation, Dataset used:      Train, Image Index:  17
```

**Comment by KotoRina** [comment] 2020-04-30 09:05
My English isn't that good, but I'll try. So far, I have solved the problem by taking the folder out of the project. After that, the learning process ceased to interrupt.
"Did you see the log start with [Source=ImageClassificationTrainer; before training canceled?" - No, there was no logbook.
The program started training and finished the process with the result "0%" and displayed an error.

Why it depends on changing the position of the folder - I do not understand yet.
What does "increase the training time" mean? I know that in some methods you can set the training time. In this method - I did not find it.

**Comment by LittleLittleCloud** [comment] 2020-04-30 17:10
>What does "increase the training time" mean? I know that in some methods you can set the training time. In this method - I did not find it.

This is because image classification's trainer will determine it's training time by itself, so you don't have to set it. The last time I said to increase training time is because my Russia is terrible... so I didn't know that you are using image classificaiton.

>Why it depends on changing the position of the folder - I do not understand yet.

Me neither,,, I will try if I can reproduce it

**Comment by LittleLittleCloud** [comment] 2020-04-30 17:19
I'm unable to reproduce it on my PC.
my folder structure is like this
![image](https://user-images.githubusercontent.com/16876986/80739803-eef13200-8acb-11ea-9c9e-996297af7261.png)

where image folder is fruits, which has this folder structure
![image](https://user-images.githubusercontent.com/16876986/80739838-003a3e80-8acc-11ea-9750-ac87a8c75517.png)

Can you provide more detailed info,,,, like the folder structure for your project? Thanks

**Comment by LittleLittleCloud** [comment] 2020-05-12 17:19
@KotoRina I'm going to close this issue, feel free to reopen it if you still have questions

**Closed by LittleLittleCloud** 2020-05-12 17:19 UTC
Labels: Customer Reported
