### ISSUE TITLE
Specified label column 'Sentiment' was not found.

### ISSUE THREAD

**Issue by cgs041328** [dotnet/machinelearning-modelbuilder#837] opened 2020-06-18 02:20 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.1.0.2026302
 - Visual Studio Version: Microsoft Visual Studio Enterprise 2019 Version 16.6.2

**Describe the bug**
Model builder error: Specified label column 'Sentiment' was not found.
Scenario: Sentiment Analysis
Data: wikipedia-detox-250-line-data.tsv
Label: Sentiment
Features: SentimentText

**Comment by thackman7** [comment] 2020-06-24 21:35
I've had a number of different issues since updating to Visual Studio 16.6.0 and 16.6.1
Right now I'm getting the same error when using classification on the Iris toy dataset.
_Specified label column 'IrisType' was not found._

![1 Setup](https://user-images.githubusercontent.com/65692262/85629464-f18d8500-b63f-11ea-9ab6-3d32cc3240a9.JPG)

![2 Train](https://user-images.githubusercontent.com/65692262/85629477-f6eacf80-b63f-11ea-8103-6a3fbebd6e39.JPG)

![3 New Error](https://user-images.githubusercontent.com/65692262/85629482-f94d2980-b63f-11ea-9e25-42fa7abbdc40.JPG)

**Comment by beccamc** [comment] 2020-08-17 21:20
@thackman7 Sorry for the delay in response on this issue. Are there any special characters in the header? For example, is the value actually "Iris-Type"?

**Comment by thackman7** [comment] 2020-08-17 21:34
There are no special characters in the headers but there is a dash in the category values. This is the first few lines of the iris data file. This is the classic iris flower classification dataset and I've used it successfully to test various scenarios in ML.Net Model Builder. Then sometime around mid May I guess, model builder stopped working on all of my projects. I've tried updating Visual Studio several times. I'm on 16.6.5 but nothing seems to fix this issue.

sLength,sWidth,pLength,pWidth,IrisType
5.1,3.5,1.4,0.2,Iris-setosa
4.9,3,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5,3.6,1.4,0.2,Iris-setosa

**Comment by cliff-pennalligen** [comment] 2020-08-19 22:36
Same issue.  Log file attached.

I was following the ML.NET tutorial exactly but with Value Prediction selected instead of Text Classification
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/intro

Here is the log file:
[ML log file.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/5099671/ML.log.file.txt)

My Visual Studio version is 16.7.2

Please unkill this feature :)

**Comment by cliff-pennalligen** [comment] 2020-08-19 22:56
found the issue in my case - I had spaces in my column names e.g. "Reagent Flow rate" in the CSV file.  When the csv data was imported, the spaces were converted to underscores e.g.  Reagent_Flow_rate.  By replacing the spaces in the CSV column headers, the error went away.  Perhaps it's searching for the modified column names instead of the original ones when reading the file?

**Comment by beccamc** [comment] 2020-08-24 22:50
@cgs041328 We had a few bugs in our header logic that I've fixed. Testing the data you provided on the new logic, it works! It could be that I can't reproduce the problem for some other reason, but I think it's fixed. The main problem was Model Builder mis-identified header/no header. This could be the case with some of the other data problems you've experienced.  

@cliff-pennalligen Sorry you ran into this problem! Definitely seems like the problem was the spaces. This should also be resolved by the fixes I've mentioned above, and my testing shows it as fixed.

We'll be releasing the new bits by the end of the week. I'll circle back then to see these are both resolved. Thank you both for reporting!

**Comment by cronz** [comment] 2020-09-11 02:43
I used Microsoft Visual Studio Community 2019 Version 16.7.3, tried to run the example of wikipedia-detox-250-line-data.tsv, also I imported this tsv to sql server table, both were failed with the same message

Specified label column 'Sentiment' was not found

It's the first example for ML.NET, blocked

**Closed** 2020-09-11 18:45 UTC
Labels: Customer Reported

**Comment by cecchettia** [comment] 2020-12-27 21:40
I am having the same problem in ML.NET Model Builder 
In this version 16.8.3 -  the "Pick a scenario" page differs- text classification is missing
I tried both Sentiment Analysis and Custom Scenario. 
I tried reinstalling ML_NET Model Builder preview. Made sure ML.NET preview was enabled under "Preview Features"

I tried the suggestions above and a few found in other forums, created a new file with only 19 lines, removed the tabs and replace with commas, Made sure the header column names contained no spaces.
Still getting the error:  "Specified label column 'Sentiment' was not found."
Any thoughts on what I can try next?
Thank you
