### ISSUE TITLE
 shows warning to upgrade from v1.7.1 to v1.7.0 ???

### ISSUE THREAD

**Issue by Elantonio** [dotnet/machinelearning-modelbuilder#2088] opened 2022-04-06 15:29 UTC
**System Information win10 intel i9:**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- shows warning to upgrade from v1.7.1 to v1.7.0 ???
- Clear description of the problem:

**To Reproduce**
1. use 1.7.1
2. use mbconfig
3. walk the steps
![image](https://user-images.githubusercontent.com/7442635/162001708-a37703f8-6fb8-4302-973c-61483cce2992.png)

**Expected behavior**
do not warn when current version is higher

**Screenshots**
![image](https://user-images.githubusercontent.com/7442635/162001708-a37703f8-6fb8-4302-973c-61483cce2992.png)

**Additional context**

**Comment by beccamc** [comment] 2022-04-14 21:00
@v-Hailishi Can you create a new project with ML.NET version 1.7.1 and see if we show an update message like the above?

**Comment by v-Hailishi** [comment] 2022-04-15 08:11
@beccamc Verified on the latest main branch 16.13.5.2221401, the issue is not repro for both of VS2019&2022.
![#2088](https://user-images.githubusercontent.com/99375895/163544338-2e6f01da-24cb-4d45-ab7b-593d98ef9d9c.gif)

**Comment by beccamc** [comment] 2022-04-15 16:13
@Elantonio What version of Model Builder are you using? What type of project is it?

**Comment by Elantonio** [comment] 2022-04-19 07:26
> @Elantonio What version of Model Builder are you using? What type of project is it?

1.71 and it is a priceprediction project

**Comment by HashemGo** [comment] 2022-04-22 12:38
We have the same problem after any updates without any fix for now

I reported this issue from 1.6.0 to 1.7.0 now we have this issue after update from 1.7.0 to 1.7.1 
https://github.com/dotnet/machinelearning-modelbuilder/issues/1929
we can't create new solution for all our models after any update to solve this big issue.

This is a bug
if you have a solution with many projects for ML
if you try training one of them the project copy namespace from another that's wired!, The projects not connected
also if you have version 1.6 and another project have version 1.7 the problem showing up

**Comment by HashemGo** [comment] 2022-04-22 13:16
Is there any explain why the project MlApi add zip files on project Scraper, I didn't add any project to another as Dependencies
also, I upgraded from 1.7.0 to 1.7.1 and still say 

Updating nuget dependencies...
Starting update NuGet dependencies async.
Installing nuget package, package ID: Microsoft.ML, package Version: 1.7.0

this bug make me crazy, for now we can't use Ml on live project because this issue

![image](https://user-images.githubusercontent.com/42634137/164720675-8c02c346-696c-4cf1-8000-b96bfc84badf.png)

**Comment by beccamc** [comment] 2022-04-26 23:07
Looks like we aren't selecting the correct project in our dependency logic (make bad assumption that there is only one project?). We should fix this for the next release.

**Comment by beccamc** [comment] 2022-04-26 23:39
Issue that would be nice to fix at the same time https://github.com/dotnet/machinelearning-modelbuilder/issues/1918

**Comment by HashemGo** [comment] 2022-04-27 00:18
Thanks, we are waiting
Also, please check screenshot 
![image](https://user-images.githubusercontent.com/42634137/165412013-6790b017-43e9-4582-9bfe-4b88753cd06b.png)

##1 the model can not read the path, you can see the model create the class on the right path but zip file path in  **_.consumption.cs_** file not right 
`private static string MLNetModelPath = Path.GetFullPath("**StatementType.zip**");`
**but it should be** 
`private static string MLNetModelPath = Path.GetFullPath("**./Training/NLP/StatementType.zip**");`

that create another error, told us the zip file not found
and see this files all the time like this
![image](https://user-images.githubusercontent.com/42634137/165412761-9184f8dd-3aa6-4d67-89bc-c4b148be69e6.png)


##2
installed Visual Studio 2022 again then create new project with ML Model, we found the default version 1.7.0
we update every thing but still show this issue **shows warning to upgrade from v1.7.1 to v1.7.0**

I hope my information help ml.net team, because this bugs make us in a bad day and lost a lot of time to find solution, but we didn't find anything to help us

Thanks

**Comment by Elantonio** [comment] 2022-04-27 10:34
Great support!
thnks.

**Comment by LittleLittleCloud** [comment] 2022-05-10 21:45
We are targeting at v1.7.1 now

**Comment by beccamc** [comment] 2022-05-13 19:51
A fix for this has been released! Please test it out.  @HashemGo let me know if this solves all your issues. If not, can you file a new issue and we will work on addressing those problems. Thanks!

**Closed by beccamc** 2022-05-13 19:51 UTC
Labels: Priority:0, Reported by: Customer, Multiple Requests
