### ISSUE TITLE
Ran into an error when running Machine learning application for wikipedia data prediction by following the instructions

### ISSUE THREAD

**Issue by jobinvargheset** [dotnet/machinelearning-modelbuilder#205] opened 2019-07-30 05:52 UTC
Ran into an error when running Machine learning application for wikipedia data prediction by following the instructions provided in "https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume". 

The screenshot of the error is posted along with this email

![Problem with ML](https://user-images.githubusercontent.com/53462813/62103980-d8f3de00-b2bb-11e9-94da-2cd736835ec2.jpg)

**Comment by rustd** [comment] 2019-08-07 20:55
@jobinvargheset can you please provide the following information which will help us debug this issue.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by JakeRadMSFT** [comment] 2019-09-20 21:24
Resolving issue because we haven't received a response. If you're still having this issue, please re-open and include the requested details.

Cheers,
Jake

**Closed by JakeRadMSFT** 2019-09-20 21:24 UTC
Labels: Customer Reported
