### ISSUE TITLE
Training process fails immediately with no useful output details

### ISSUE THREAD

**Issue by Renato89** [dotnet/machinelearning-modelbuilder#384] opened 2019-11-25 18:17 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

I've tried to train an image classification model with the 60000 MNIST datasets. I've put the data in the folder structure as written, and in fact, the data preview showed that the data had been read correctly.

The problem occurs when I push "Start Train". After one second it fails with the following message on the status field: "Failed. See more in Output Pane". But in the output it shoes only this: 
"|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |".
Nothing useful for taking further action.

**Comment by beccamc** [comment] 2019-11-25 23:28
Sorry you've run into this problem Renato! I know the MNIST dataset isn't downloadable in a standard image format.  Based on the fact you got a data preview working it sounds like you unpacked the files.  What image file type did you save them as in the folders? 

 I'll try to pull this dataset and try it on my machine.

**Comment by Renato89** [comment] 2019-11-25 23:44
Yes, I unpacked it. The format is jpeg. Anyway, it worked using 10000 images instead of 60000.
The resulting folder from the bigger dataset after the unpacking occupies almost 250 MB against the 40 MB fo the smaller one. Maybe there is a limit in image recognition that I missed.

**Comment by beccamc** [comment] 2019-11-26 16:36
@LittleLittleCloud Do you know anything about size limits for image recognition?

**Comment by LittleLittleCloud** [comment] 2019-12-02 17:56
As far as I know, there's no such limitation in that. I'm gonna double check though

**Comment by tjshin** [comment] 2019-12-04 15:37
I tried using the corefx-issues-train.tsv file from the MulticlassClassification-GitHubLabeler sample code on my console app. I am getting the same error. No useful information on the Output pane.

**Comment by KodaPOwER** [comment] 2019-12-06 09:27
Hi,

i'm trying to make a binary-classification model. Data come form a csv file (small sample here [dati-avvisi.zip](https://github.com/dotnet/machinelearning-samples/files/3931369/dati-avvisi.zip)) that has 5 columns:
ID | CODICE-HOST | DESCRIZIONE | TITOLO | Inserito
Inserito should by my label column, and Descrizione and Titolo are my features.
Immediately after i hit train in the model builder i have this:
![image](https://user-images.githubusercontent.com/9638822/70311328-bfd2df00-1811-11ea-9cf6-833cfd48fac7.png)

Can you help my to track down what is the error? Is it a bug? 

I've tried with the sentiment analysis example and it work. It work even with another similar dataset I tried yesterday. I really can't see where is the problem....

I use Visual studio 2019 updated to the latest version.

**Comment by JakeRadMSFT** [comment] 2019-12-20 21:14
Related to #402

**Comment by JakeRadMSFT** [comment] 2020-01-03 21:50
@KodaPOwER Sorry for the delayed response! 

Are you saying it worked for Sentiment Analysis but didn't work for Custom -> Binary Classification?

**Comment by LittleLittleCloud** [comment] 2020-01-06 19:36
@KodaPOwER I'm able to reproduce the bug you report. I will take a look, thanks for your feedback

**Comment by KodaPOwER** [comment] 2020-01-07 13:08
@LittleLittleCloud ok, thank you for the hint!
I already tried with a tab separated dataset but i get the same error, maybe the problem is the \n chars and the ones with 6 cols. Especially this one is strange because the dataset it's an export directly from JetBrains DataGrip results window...
Maybe can also be useful to have a meaningful error message from the tool :)

Regards, and thanks again for your help

**Comment by LittleLittleCloud** [comment] 2020-01-07 18:56
The latest released ModelBuilder doesn't include the error handler PR, therefore it won't through an error window to notify users of the fail reason.  That PR will be included in the next release.

**Closed** 2020-02-23 23:38 UTC
