### ISSUE TITLE
Enable ML.NET Model Builder not working

### ISSUE THREAD

**Issue by lanarosenthal** [dotnet/machinelearning-modelbuilder#776] opened 2020-05-28 17:48 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

"Would you like to enable the ML.NET Model Builder preview feature so you can add Machine Learning to your .NET projects?  Enable ".  I click enable and restart VS, but it still won't work. VS 16.6

**Comment by Erol444** [comment] 2020-05-30 21:00
Same problem. After clicking enable, you an "Options" popup on "Preview Features". Even if you check everything (and restart), after trying to add machine learning to the project you just get another "Would you like to enable...". Latest VS, tried restarting VS and computer.

**Comment by KeithT** [comment] 2020-06-01 15:51
Same thing here. This is blocking for model builder installation and use.

**Comment by lanarosenthal** [comment] 2020-06-01 17:02
@KeithT @Erol444 It is a bug in Visual Studio 16.6. Try it on Visual Studio 16.7 instead and it should work - https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**Comment by Erol444** [comment] 2020-06-01 17:20
> 
> 
> @KeithT @Erol444 It is a bug in Visual Studio 16.6. Try it on Visual Studio 16.7 instead and it should work - https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview
Thanks, works now 👍

**Comment by JakeRadMSFT** [comment] 2020-06-01 23:45
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

Duplicate of: #764

**Closed by JakeRadMSFT** 2020-06-01 23:45 UTC

**Comment by acrigney** [comment] 2021-07-23 12:01
I have this issue again with VS2022 preview 1 and 2.1
