### ISSUE TITLE
Not able to enable ML.NET preview feature

### ISSUE THREAD

**Issue by gregmulvihill** [dotnet/machinelearning-modelbuilder#780] opened 2020-05-30 21:32 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

---

OS Name Microsoft Windows 10 Pro Version 10.0.18362 Build 18362

While following the steps on the page referenced above, I encountered an issue that keeps behaving like I am at the beginning of the installation step, no matter how many times, ways, or versions I try to install.

When I click on Machine Learning in the context menu of the project, the following message is displayed: "Would you like to enable the ml.net model builder preview feature so you can add machine learning to your .net projects? Enable"

The Enable link opens the Options dialog, but there is no related option to enable.  The closest option, which was already enabled, is, "Use previews of the .NEW Core SDK (requires restart)".

I have tried downloading the installer from https://marketplace.visualstudio.com/items?itemName=MLNET.07, as well as installing via VS2019 (16.6.0) "Manage Extensions" dialog.  Both installations result in the same message.

**Comment by d3vi73ck** [comment] 2020-05-31 00:05
Hello, 
I m currently facing the same problem on vs 2019 . i haven't found a solution yet. 
Will keep you updated.

**Comment by supimon** [comment] 2020-05-31 07:48
same issue here.

**Comment by gregmulvihill** [comment] 2020-05-31 16:33
I tried completely removing ML.NET via the Visual Studio Installer, then installed only the latest vsix, but received the same results. After removing the vsix installed ML.NET, I tried the Visual Studio Installer and noticed there are 2 entries for ML.NET on the second tab.  I installed both, same results.  I installed the latest vsix installer as well. Same results.  I did a similar test with Use previews of the .NET Core SDK checked and unchecked, same results.  I could not find any source code to look through and am not sure what else to try at this pint. Suggestions?

**Comment by lanarosenthal** [comment] 2020-06-01 17:06
@gregmulvihill @d3vi73ck @supimon I believe it is a bug in Visual Studio 16.6. I tried it on Visual Studio 16.7 (Preview) instead and it worked - https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview

**Comment by d3vi73ck** [comment] 2020-06-01 19:33
@lanarosenthal +1 , problem solved by updating VS to 16.6.1.
Thank you.

**Comment by JakeRadMSFT** [comment] 2020-06-01 23:44
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

Duplicate of: #764

**Closed** 2020-06-01 23:44 UTC
