### ISSUE TITLE
AutoML Unable to infer column types of the file when column# exceeds 10000

### ISSUE THREAD

**Issue by LetterFirst** [dotnet/machinelearning-modelbuilder#192] opened 2019-07-24 10:36 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1907.1703
 - Visual Studio Version: Visual Studio 2017 15.9.14

**Describe the bug**
csv file get an error when I try to load it "Unable to infer column types of the file provided"
You can get csv file from https://github.com/LetterFirst/DataSet

**To Reproduce**
1. Click "Custom Scenario" and "Select a file"

**Screenshots**
![0](https://user-images.githubusercontent.com/53216682/61787071-4e206880-ae0f-11e9-964f-1951525266a3.PNG)

Thank you for help me!

**Comment by JakeRadMSFT** [comment] 2019-07-31 21:02
Please investigate root cause.

**Comment by justinormont** [comment] 2019-08-01 08:30
Dataset has 10,164 columns. 

Currently, the AutoML code has an arbitrary limit of the [max number of columns](https://github.com/dotnet/machinelearning/blob/a15aaa73ffa3798d4ab6c79672a7d3859d36030b/src/Microsoft.ML.AutoML/ColumnInference/ColumnTypeInference.cs#L19-L22) set to 10k. 

I thought we had a PR out to change this limit to 200k and add automatic column grouping above 20k, though I can't seem to locate it.

**Comment by LetterFirst** [comment] 2019-08-01 09:22
Thank you very much! Have a nice day

**Comment by LittleLittleCloud** [comment] 2019-08-07 23:16
Is there a way to find out which cause the infer error from AutoML? (can't find any from source code though). Maybe we can add an infer Error type for that?

**Comment by evo11x** [comment] 2019-08-09 11:03
I am also getting this error from a CSV file exported with this function

  ```
using (var stream = File.Create("c:\\temp\\aidata.csv"))
                 mlContext.Data.SaveAsText(trainData, stream);          

```
There are 12 columns and some of them are vector types. The data model is valid as the prediction works.

**Comment by LittleLittleCloud** [comment] 2019-08-12 18:16
> In my CSV file there are 12 columns and some of them are vector types. The data model is valid as the prediction works.

Can you check if vector value is being put into a pair of double quote, like "[val1, val2, val3]", because CSV uses comma as separator, and without double quote, comma in vector-type value will cause a parser error.

**Comment by LittleLittleCloud** [comment] 2020-04-21 18:36
#### Root cause:
AutoML has a limit of inferring up to 10000 columns, in this case, unselect 200 columns and ModelBuilder will (just) work.

Such problem also exists in ML.Net CLI since it also uses AutoML to do column inference.

#### Problems.
the user experience is awful when having 9999 columns in model builder, UI is slow and ModelBuilder window will flash when I select label. (though it's not crash thanks to @beccamc 's work)

#### Proposal 
- remove the restriction of 10000 in AutoML/ through an error in ModelBuilder when user's column exceeds 10000
- Update/improving ModelBuilder Data page to make it work well with dataset with bunch of columns.

**Comment by LittleLittleCloud** [comment] 2021-04-28 19:52
This issue is no longer exists. Feel free to close it.

**Comment by evo11x** [comment] 2021-04-28 22:50
> > In my CSV file there are 12 columns and some of them are vector types. The data model is valid as the prediction works.
> 
> Can you check if vector value is being put into a pair of double quote, like "[val1, val2, val3]", because CSV uses comma as separator, and without double quote, comma in vector-type value will cause a parser error.

sorry for the delay, I missed your questions.
The data is tab delimited with this header

```
#@ TextLoader{
#@   header+
#@   sep=tab
#@   col=Col1:R4:0
#@   col=Col2:R4:1
#@   col=Col3:R4:2-101
#@   col=Col4:R4:102-201
#@   col=Col5:R4:202-301
#@   col=Col6:R4:302-401
#@   col=Col7:R4:402-501
#@   col=Col8:R4:502-601
#@ }
```

This is the way ML.Net saves it as CSV/text, and it's very strange that ML itself then cannot process it.

**Comment by vzhuqin** [comment] 2021-04-30 09:26
This issue not repro on main branch: https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.21.2122903
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

Steps:
1. Download the data set from: https://github.com/LetterFirst/DataSet
2. Select Text classification and Local (CPU);
3. Navigate to Data page, select File and click "Browser..." to load the dataset;
4. About 15 minutes, the data input is complete.
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/b81b65e1-9481-4ec5-9a5d-92c44929ba8c)

**Comment by beccamc** [comment] 2021-04-30 17:08
Closing as this issue is fixed. @evo11x Great question! We are tracking supporting that fie format in this issue - https://github.com/dotnet/machinelearning-modelbuilder/issues/946

Thanks for reporting!

**Closed by beccamc** 2021-04-30 17:08 UTC
Labels: Dataset problem
