### ISSUE TITLE
Show Microsoft Visual Studio error when open model builder on VS2022 Preview 3.1.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1759] opened 2021-09-02 09:41 UTC
**System Information (please complete the following information):**
- ML.Net Model Builder: 16.7.3.2143104 (Main Branch)
- Windows OS: Windows-10-Enterprise-21H1
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 3.1

**Describe the bug**
- On which step of the process did you run into an issue: Open model builder
- Clear description of the problem: Can add model builder by right click on the project successfully, but the model builder cannot be opened, it displays Microsoft Visual Studio error: The type initializer for 'Microsoft.ML.ModelBuilder.TrainingConfigurationHelper' threw an exception.

**To Reproduce**
1. Download Microsoft.ML.ModelBuilder.Gallery.Dev17 from latest main build: [link](https://devdiv.visualstudio.com/_apis/resources/Containers/8587663/VSSetup_Release17?itemPath=VSSetup_Release17%2FMicrosoft.ML.ModelBuilder.Gallery.Dev17.vsix)
2. Install model builder from downloaded VSIX Installer;
3. Select Create a new project from the Visual Studio 2022 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Find that the model builder was created but not opened, then double click the model builder, prompts Microsoft Visual Studio dialog said: The type initializer for 'Microsoft.ML.ModelBuilder.TrainingConfigurationHelper' threw an exception.

**Expected behavior**
Model builder can be added and opened without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/131817094-49e3ecdc-a35f-4832-b9c6-3eadd95dae13.png)

**Additional context**

- This issue not occurs on older model builder build 16.7.3.2142702 from: [link](https://devdiv.visualstudio.com/_apis/resources/Containers/8559769/VSSetup_Release17?itemPath=VSSetup_Release17%2FMicrosoft.ML.ModelBuilder.Gallery.Dev17.vsix)
![image](https://user-images.githubusercontent.com/81727020/131823379-fa533122-7d25-4e14-bd94-04ed8bf4a2bd.png)

- This issue not occurs on Microsoft Visual Studio Enterprise 2022 Int Preview (64-bit): Version 17.0.0 Preview 4.0 [31630.363.main]
![image](https://user-images.githubusercontent.com/81727020/131823621-bddfbd4b-f7c4-4cdf-a8bd-cd4d47f9af20.png)

**Comment by zewditu** [comment] 2021-09-02 23:39
This happens for Vs 2022  preview 4.0  and model builder version:16.7.4.2145201
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/b5b1fbfe-4a11-480a-a0a4-2d0ffef73e2c)

**Comment by beccamc** [comment] 2021-09-07 17:56
@JakeRadMSFT Do we care about fixing VS 2022 Preview 3.1?

@zewditu That seems to be a different issue? If you get a repro can you please open a new issue? Include the mbconfig file that is causing the problem

**Comment by zewditu** [comment] 2021-09-08 05:34
Currently, I am in preview 5 of vs2022, I am not able to back preview 4, and I am not sure if the issues still exist. In preview 5 the issue does not exist

**Comment by zewditu** [comment] 2021-09-14 04:20
For my case, the issue does not reproduced in preview 4 any more

**Comment by beccamc** [comment] 2021-09-16 19:10
Closing. We can open a new issue if there are new repro steps.

**Closed by beccamc** 2021-09-16 19:10 UTC
Labels: Priority:1, Test Team, VS2022
