### ISSUE TITLE
Recommendation: Some trainer numbers are missing and non-continuously on the Output window.

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2413] opened 2022-12-13 01:37 UTC
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 16.14.0.2260701 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.4.1)
.Net: 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
Some trainer numbers are missing and non-continuously on the Output window.

**Data Source**
https://testpass.blob.core.windows.net/test-pass-data/recommendation-ratings.csv

**To Reproduce**

  1. Select Create a new project from the Visual Studio 2022 start window.
  2. Choose the C# Console App (.NET Core7.0) project template.
  3. Add model builder by right click on the project.
  4. Select **Recommendation** scenario.
  5. On Data page, select the data source and choose "**rating**" column as label.
  6. On the Train page, click "Advanced training options..." link, then choose any metric and save it.
  7. Click "Start training" button to complete the training and then check the output window.

**Expected behavior**
Trainer numbers should be continuously on the Output window.

**Screenshot**
![image](https://user-images.githubusercontent.com/99375895/207204747-783a2a25-2bca-4894-930c-1ffda9e1df80.png)

**Comment by luisquintanilla** [comment] 2022-12-14 21:52
Thanks for reporting this issue @v-Hailishi. Closing as duplicate of #2313

**Closed by luisquintanilla** 2022-12-14 21:52 UTC
Labels: Priority:1, Reported by: Test
