### ISSUE TITLE
Exception while auto-train with regression task

### ISSUE THREAD

**Issue by smigielns** [dotnet/machinelearning-modelbuilder#363] opened 2019-11-22 15:03 UTC
Hello

I would like to report a below error. I have tried also to run it using Visual Studio and ML.NET Model Builder but the result was the same.

![obraz](https://user-images.githubusercontent.com/16755569/69435956-c4db5d00-0d40-11ea-803d-60136aabcae1.png)

[debug_log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/3880057/debug_log.txt)

**Comment by LittleLittleCloud** [comment] 2019-11-22 22:43
Can we have your datasets, it should be something wrong in automl

**Comment by smigielns** [comment] 2019-11-25 08:14
Yes, of course.

"Price" is a column to predict.
[testujemy.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/3885411/testujemy.zip)

I'm not familiar with ML. I have ran the test just to see how it works so data file may be also not correct.

I hope that helps.

**Comment by LittleLittleCloud** [comment] 2019-12-02 19:03
I've run the experiment for several time and can't reproduce the error... Could you also try re-run that experiment and see if that error occur? 
and BTW could I have the version of your mlnet cli, and the test file ".\test_walidaca..csv"? 
Thanks!

**Comment by smigielns** [comment] 2019-12-09 09:15
[test_walidacja.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/3938605/test_walidacja.zip)

My mlnet version is:
0.15.28007.4 @BuiltBy: dlab14-DDVSOWINAGE054 @Branch: features/automl @SrcCode: https://github.com/dotnet/machinelearning/tree/dc9a9b7ffcaf636541fe997c59f3bfdda57501e5+dc9a9b7ffcaf636541fe997c59f3bfdda57501e5

I have run it also using Visual Studio and the error occurs when I increase the 'Time to train' value. It stops after 8th iteration - the same as when I run it with CLI, the log file you can find in the first message in this conversation.

In below example I used only 'testujemy.csv' file.

![ml_error](https://user-images.githubusercontent.com/16755569/70422881-c1e4aa00-1a6c-11ea-90bf-f91d0a9e0926.gif)

Have a good day!

**Comment by JakeRadMSFT** [comment] 2020-01-03 20:20
@smigielns thanks for the added information. We'll try to reproduce the issue.

**Comment by LittleLittleCloud** [comment] 2020-01-07 19:49
I can reproduce the bug you encountered now

**Comment by LittleLittleCloud** [comment] 2020-01-07 21:19
It's a bug in Sweepable parameters, in [SweepableParamAttributes](https://github.com/dotnet/machinelearning/blob/7a4372e1dda8f5d5c070ffce6bd1929216939d90/src/Microsoft.ML.AutoML/Utils/SweepableParamAttributes.cs#L148), if `valueText` is "0,034456" (represented in Russian format) or something, it will be parsed into 34456 instead of 0.034456, If that paramater is significant ( like learning_rate), such error will cause bad training result ( score be -inf). But it won't break pipeline because it's not an exception. But in the next handling training result [step](https://github.com/dotnet/machinelearning/blob/7a4372e1dda8f5d5c070ffce6bd1929216939d90/src/Microsoft.ML.AutoML/Experiment/Runners/CrossValSummaryRunner.cs#L63), it will throw an exception because there's no legitimate training result and the `bestFoldIndex ` will be -1.

**Comment by LittleLittleCloud** [comment] 2020-01-07 22:33
This will be fixed in the next release, regards

**Closed** 2020-02-23 23:38 UTC
Labels: Customer Reported, Partner
