### ISSUE TITLE
System errors were found in at least one of the child runs.

### ISSUE THREAD

**Issue by pinnaclx** [dotnet/machinelearning-modelbuilder#2054] opened 2022-03-07 15:41 UTC
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by luisquintanilla** [comment] 2022-03-08 19:26
Might be related to #2052

**Comment by luisquintanilla** [comment] 2022-03-11 18:23
Closing this issue as duplicate of #2055

**Closed by luisquintanilla** 2022-03-11 18:23 UTC
Labels: Priority:0
