### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Leozaur1808** [dotnet/machinelearning-modelbuilder#1513] opened 2021-06-16 14:04 UTC
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.6.2130907
 - Visual Studio Version (if applicable): 2019

**Describe the bug**
I have actually two bugs:
1)predicted value doesn't change 
2)error when I am trying to train it again

**To Reproduce**
1) train
2)check are predicted values are changing or not
3)if not go to train again
4)error appears
**Expected behavior**
Just need to work

**Screenshots**
![image](https://user-images.githubusercontent.com/33627925/122229313-4bc2ce00-cec1-11eb-9dc7-d32ec41e3822.png)
![image](https://user-images.githubusercontent.com/33627925/122229374-57ae9000-cec1-11eb-99fe-31f6c67005f3.png)

**Additional context**
My data set:
[DataSber.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6663443/DataSber.txt)
 Error number:
 в Microsoft.ML.ModelBuilder.ToolWindows.EvaluateTabControl.TextBox_TextChanged(Object sender, TextChangedEventArgs e)
   в System.Windows.Controls.TextChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.Controls.Primitives.TextBoxBase.OnTextChanged(TextChangedEventArgs e)
   в System.Windows.Controls.Primitives.TextBoxBase.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
   в System.Windows.Controls.TextBox.OnTextContainerChanged(Object sender, TextContainerChangedEventArgs e)
   в System.Windows.Documents.TextContainerChangedEventHandler.Invoke(Object sender, TextContainerChangedEventArgs e)
   в System.Windows.Documents.TextContainer.EndChange(Boolean skipEvents)
   в System.Windows.Documents.TextContainer.System.Windows.Documents.ITextContainer.EndChange(Boolean skipEvents)
   в System.Windows.Documents.TextRangeBase.EndChange(ITextRange thisRange, Boolean disableScroll, Boolean skipEvents)
   в System.Windows.Documents.TextRange.System.Windows.Documents.ITextRange.EndChange(Boolean disableScroll, Boolean skipEvents)
   в System.Windows.Documents.TextRange.ChangeBlock.System.IDisposable.Dispose()
   в System.Windows.Controls.TextBox.OnTextPropertyChanged(String oldText, String newText)
   в System.Windows.Controls.TextBox.OnTextPropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.Controls.TextBox.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   в System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.TreeWalkHelper.InvalidateTreeDependentProperty(TreeChangeInfo info, DependencyObject d, FrameworkObject& fo, DependencyProperty dp, FrameworkPropertyMetadata fMetadata, Style selfStyle, Style selfThemeStyle, ChildRecord& childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   в System.Windows.TreeWalkHelper.InvalidateTreeDependentProperties(TreeChangeInfo info, FrameworkElement fe, FrameworkContentElement fce, Style selfStyle, Style selfThemeStyle, ChildRecord& childRecord, Boolean isChildRecordValid, Boolean hasStyleChanged, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   в System.Windows.FrameworkElement.InvalidateTreeDependentProperties(TreeChangeInfo parentTreeState, Boolean isSelfInheritanceParent, Boolean wasSelfInheritanceParent)
   в System.Windows.FrameworkElement.OnAncestorChangedInternal(TreeChangeInfo parentTreeState)
   в System.Windows.TreeWalkHelper.OnAncestorChanged(DependencyObject d, TreeChangeInfo info, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в MS.Internal.PrePostDescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   в MS.Internal.PrePostDescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   в System.Windows.TreeWalkHelper.InvalidateOnTreeChange(FrameworkElement fe, FrameworkContentElement fce, DependencyObject parent, Boolean isAddOperation)
   в System.Windows.FrameworkElement.OnVisualParentChanged(DependencyObject oldParent)
   в System.Windows.Media.Visual.FireOnVisualParentChanged(DependencyObject oldParent)
   в System.Windows.Media.Visual.RemoveVisualChild(Visual child)
   в System.Windows.Media.VisualCollection.DisconnectChild(Int32 index)
   в System.Windows.Media.VisualCollection.Clear()
   в System.Windows.Controls.UIElementCollection.ClearInternal()
   в System.Windows.Controls.Panel.ClearChildren()
   в System.Windows.Controls.Panel.EnsureEmptyChildren(FrameworkElement logicalParent)
   в System.Windows.Controls.Panel.OnItemsChangedInternal(Object sender, ItemsChangedEventArgs args)
   в System.Windows.Controls.Panel.OnItemsChanged(Object sender, ItemsChangedEventArgs args)
   в System.Windows.Controls.ItemContainerGenerator.OnRefresh()
   в System.Windows.Controls.ItemContainerGenerator.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   в System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   в System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   в System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   в System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   в System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   в System.Windows.Controls.ItemCollection.SetCollectionView(CollectionView view)
   в System.Windows.Controls.ItemCollection.SetItemsSource(IEnumerable value, Func`2 GetSourceItem)
   в System.Windows.Controls.ItemsControl.OnItemsSourceChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   в System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.Activate(Object item)
   в System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
   в System.Windows.Data.BindingExpression.HandlePropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.Data.BindingExpressionBase.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.Data.BindingExpression.OnPropertyInvalidation(DependencyObject d, DependencyPropertyChangedEventArgs args)
   в System.Windows.DependentList.InvalidateDependents(DependencyObject source, DependencyPropertyChangedEventArgs sourceArgs)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.TreeWalkHelper.OnInheritablePropertyChanged(DependencyObject d, InheritablePropertyChangeInfo info, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1._VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(FrameworkElement fe, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.VisitNode(DependencyObject d, Boolean visitedViaVisualTree)
   в System.Windows.DescendentsWalker`1.WalkLogicalChildren(FrameworkElement feParent, FrameworkContentElement fceParent, IEnumerator logicalChildren)
   в System.Windows.DescendentsWalker`1.WalkFrameworkElementLogicalThenVisualChildren(FrameworkElement feParent, Boolean hasLogicalChildren)
   в System.Windows.DescendentsWalker`1.IterateChildren(DependencyObject d)
   в System.Windows.DescendentsWalker`1.StartWalk(DependencyObject startNode, Boolean skipStartNode)
   в System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   в System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   в System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   в System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   в System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   в System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   в MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   в MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   в MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   в MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   в System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   в System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   в System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   в Microsoft.ML.ModelBuilder.Observable.ObservableModel.RaisePropertyChangedEvents(IEnumerable`1 properties)
   в Microsoft.ML.ModelBuilder.Observable.ObservableModel.NotifyPropertyChanged(String propertyChanged)
   в Microsoft.ML.ModelBuilder.Observable.ObservableModel.Set[T](T newValue, String caller)
   в Microsoft.ML.ModelBuilder.Observable.ObservableModel.<HandlePropertyUpdateAsync>d__25.MoveNext()
- [ ]

**Comment by LittleLittleCloud** [comment] 2021-06-16 18:37
Hi @Leozaur1808 
Thanks for using the model builder and giving feedback.

The first bug (predict value is not changed) is actually not a bug given that the r-squre is so close to zero, which indicates that `0`%  portion of variance from predicted value can be explained by the input data. And in that case, it's not strange that the predicted value doesn't reflect the input data.

We are aware of the second bug and are working on a fix for that, and before the fix is merged in, you should be able to retrain model by closing that error window or reopen `.mbconfig` file.

Happy coding!

**Comment by Leozaur1808** [comment] 2021-06-16 18:40
But actually I can see obvious connection between appearing of second bug and unchangable value

**Comment by Leozaur1808** [comment] 2021-06-16 18:41
I know I have r squared below zero, but actually in som cases the value changes even with that

**Comment by LittleLittleCloud** [comment] 2021-06-16 20:43
Hi @Leozaur1808 

> I know I have r squared below zero, but actually in some cases the value changes even with that
The non-zero rsquare indicates that the variation of prediction values in test dataset is not zero, but since it's quite close to zero, the variation is also quite small, and they should be very close to the average of actual values in test dataset (close to 0.5)

If you want to see the change in label, you can try some random values In my case, I got r-square ~ -0.008 for a 10s training, and the predicting value is stick to 0.47 no matter what value I tried at first. But after I try some wild values, the predicted result start to change. 

![image](https://user-images.githubusercontent.com/16876986/122289810-f8905180-cea7-11eb-88a6-a8130e8d6fa6.png)

![image](https://user-images.githubusercontent.com/16876986/122289920-16f64d00-cea8-11eb-8da6-5468824cf897.png)

**Comment by vzhuqin** [comment] 2021-08-18 02:15
Still met the error dialog after clicked one scenario.
ML.Net Model Builder: 16.7.2.2141801 (Main Branch)
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a569f491-9133-432b-bcdf-faf94a0a7ed2)

**Comment by LittleLittleCloud** [comment] 2021-08-23 21:39
Not reproduced on VS2022

**Comment by vzhuqin** [comment] 2021-08-25 02:09
@LittleLittleCloud I still met this Error dialog after clicking one scenario on VS2019 and VS2022.

- ML.Net Model Builder: 16.7.2.2142301 (Main Branch)

- ![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/df873e18-7e8a-4fcb-b901-b1e9eac356cb)

- ![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/65d27863-026d-468f-9cf2-af62c967d192)
![1513 repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/3776a1cb-4c7e-4dd4-9935-9ceb78d9b212)

**Comment by vzhuqin** [comment] 2021-09-01 09:47
Still met this error after clicked one scenario on main build: 16.7.4.2143102.

![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/f143c618-1065-4abf-9e30-852c8c6df32a)

**Comment by vzhuqin** [comment] 2021-11-03 02:20
the error dialog is still prompts after clicked one scenario on latest main: 16.9.1.2155201
- Windows OS: Windows 11 Enterprise 21H2
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 7.0
![image.png](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/78d6eff2-850b-4cbd-8e82-df7f99a861d6)

**Comment by vzhuqin** [comment] 2022-01-14 08:11
Not repro this issue on main: 16.12.1.2206302

**Closed** 2022-02-07 20:46 UTC
Labels: Customer Reported, GS Tutorial
