### ISSUE TITLE
after downloading the wikipedia-detox-250-line-data.tsv it is showing error "Unsupported file type" on adding data

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#102] opened 2019-06-17 17:23 UTC
Customer reported this issue here https://github.com/dotnet/machinelearning-samples/issues/513

Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/data
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greazer** [comment] 2019-06-25 00:01
@hariharan18, We're closing this issue due to our need for further details as we are unable to reproduce. Please provide the version of Windows and Visual Studio you are running.

**Closed by greazer** 2019-06-25 00:01 UTC
Labels: Customer Reported, Pretriaged
