### ISSUE TITLE
Input String format incorrect exception while training.

### ISSUE THREAD

**Issue by bmigette** [dotnet/machinelearning-modelbuilder#627] opened 2020-03-26 15:45 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.2003.302
 - Visual Studio Version: 2019

**Describe the bug**
After training a model, Got an exception at the end. I could not go to Evaluate step.

I'm not sure about the translation of the exception, but it should be something like:
Input String format incorrect

Exception:
   à Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() dans E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:ligne 108
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() dans E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:ligne 134

**To Reproduce**
1. Create issue classification
2. Put your CSV File and pick columns
3. Start training

**Expected behavior**
No exception should be seen and process should continue

**Screenshots**

**Additional context**
Suspecting this has to do with my regional settings (French) where decimal separator is ','.

**Comment by Lewis-Fam** [comment] 2020-03-26 16:01
I received the same error following the ML tutorial (https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/data).

Visual Studio: v16.5.1
Model Builder: 16.0.2003.302

**Comment by beccamc** [comment] 2020-04-17 23:36
@Lewis-Fam Are you also in a region where the decimal separator is "," ?

**Comment by beccamc** [comment] 2020-04-20 23:26
@bmigette Could you share your dataset? I've changed my compute region and I'm not able to reproduce with the wikipedia-detox-250-line-data.tsv

**Comment by beccamc** [comment] 2020-04-20 23:40
I also tired to repro with a numbers dataset. It worked and I was able to train. If you could share your dataset that would be really helpful! 

Data:
Att1,Att2,Att3,Att4,Forgery
3.6216,8.6661,-2.8073,-0.44699,0
4.5459,8.1674,-2.4586,-1.4621,0
3.866,-2.6383,1.9242,0.10645,0

Model builder preview:
![image](https://user-images.githubusercontent.com/9122518/79809413-3f76cb80-8325-11ea-9f97-bf9451df6f83.png)

**Comment by bmigette** [comment] 2020-04-21 08:54
Here you go: https://drive.google.com/file/d/1e_bP5Pvq3SNpLR4VvynG9x6FFLjAgWrc/view?usp=sharing
I've chosen Issue classification, and selected trend_next_20 as predicted column.
Removed all trend columns in the input columns.

**Comment by beccamc** [comment] 2020-05-08 00:15
Sorry for the delay @bmigette.  I've tried with a `,` separator language on my machine and haven´t been able to reproduce. You are not the only one running into problems with `,` vs. `.` and I want to figure out the problem.

To summarize, you're training a numeric dataset that uses `.` as the decimal separator and , as the delimiter on the file (.csv). Your machine is in a language that expects `,` as the decimal separator. Training does not complete and you cannot advance to the Evaluate page because an error similar to `Input String format incorrect` is shown. This only happens sometimes (training time of 180s is okay, training time 1800s fails).

Does training fail right away, or at the end? What language is set for your VS?

**Comment by bmigette** [comment] 2020-05-08 08:32
> Sorry for the delay @bmigette. I've tried with a `,` separator language on my machine and haven´t been able to reproduce. You are not the only one running into problems with `,` vs. `.` and I want to figure out the problem.
> 
> To summarize, you're training a numeric dataset that uses `.` as the decimal separator and , as the delimiter on the file (.csv). Your machine is in a language that expects `,` as the decimal separator. Training does not complete and you cannot advance to the Evaluate page because an error similar to `Input String format incorrect` is shown. This only happens sometimes (training time of 180s is okay, training time 1800s fails).
> 
> Does training fail right away, or at the end? What language is set for your VS?

Hi,
Here's the number format of my csv:
0.6361155060774996,0.5670212392831645,0.4545838648895267,0.6762474404317713

It fails at the end of the training process. It failed every attempts (so far I made maybe 3 attempts) I have made using default time of 1800seconds. Not sure why it hasn't failed when using 180seconds.
My VS is in english.

I can't tell for sure this has to do with regional settings, but usually error with bad input format can be caused by this.

I can set my windows to US and give it a try if you want, or collect additional logs.

**Comment by beccamc** [comment] 2020-06-22 20:07
@bmigette I was able to successfully train your dataset on our latest build (16.1.0.2027905).  Do you want to give it a try and see if the problem is fixed? I think I've tested on all the configurations you might have.

**Comment by beccamc** [comment] 2020-07-08 20:14
Based on my testing this is fixed in version 16.1.0.2027905. If any comma separator users run into this again please ping we and we can reopen!

**Closed by beccamc** 2020-07-08 20:14 UTC
Labels: Customer Reported

**Comment by Sire** [comment] 2021-02-01 13:38
@beccamc Another related bug here: https://github.com/dotnet/machinelearning-modelbuilder/issues/1143
