### ISSUE TITLE
no ML dotnet window

### ISSUE THREAD

**Issue by supimon** [dotnet/machinelearning-modelbuilder#781] opened 2020-05-31 08:23 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/scenario
Operating System: windows

OS: windows 10 home (latest)
VS: version 2019 16.6

ML dotnet preview doesnt under preview features to enable it. Therefore no ML window appears to proceed further

**Comment by JakeRadMSFT** [comment] 2020-06-01 23:46
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

Duplicate of: #764

**Closed by JakeRadMSFT** 2020-06-01 23:46 UTC
