### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by infiniteloopltd** [dotnet/machinelearning-modelbuilder#665] opened 2020-04-10 07:55 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 1.4.1 (I think)
 - Visual Studio Version: 2017 Pro

**Describe the bug**
When training on a large dataset (56 features, 1.2 million rows - all floats), the ML builder crashes during "Downloading data" (from SQL server), with an OutOfMemoryException. 

The machine has 16GB or ram, and plenty of free disk space for virtual memory.

**To Reproduce**
- Create a training set of 1.2 million rows, 56 columns
- Use "Issue Classifiction" for training. 
- After pressing "Train" ML builder crashes.

**Expected behavior**
The Training should continue as normal. Virtual memory should be used if there
is insufficient RAM. 

**Screenshots**
Error retrieving SQL data: "Exception of type 'System.OutOfMemoryException' was thrown."

 at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<DownloadSqlFileAsync>b__88_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<DownloadSqlFileAsync>d__88.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.ModelBuilderDataContext.<<OnDataChanged>b__77_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabDataContext.<BuildTrainModelParametersAsync>d__138.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabDataContext.<StartTrainingAsync>d__130.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.ML.ModelBuilder.ToolWindows.TrainTabControl.<<StartTraining_Click>b__5_0>d.MoveNext()

**Additional context**
 In general, the takeaway from this should be, if the data set is too large to fit into RAM, it should use virtual memory. This will be slower, but it's better than a crash.

**Comment by beccamc** [comment] 2020-04-13 20:12
Thanks for reporting with details @infiniteloopltd! This looks like a duplicate of #647 . Please follow 647 for updates on this fix.

**Comment by beccamc** [comment] 2020-04-14 18:13
Closing this issue as duplicate. Please follow #647 for updates. Thank you for reporting!

**Closed by beccamc** 2020-04-14 18:13 UTC
Labels: Customer Reported
