### ISSUE TITLE
VS would be crash after changing "Does the data contain column headers" from "Yes" to "No".

### ISSUE THREAD

**Issue by v-Hailishi** [dotnet/machinelearning-modelbuilder#2643] opened 2023-05-19 07:58 UTC
**System Information (please complete the following information):**
Windows OS: Windows-11-Enterprise-22H2
ML.Net Model Builder 2022: 17.16.0.2326803 (Main Build)
Microsoft Visual Studio Enterprise: 2022(17.5.5)
.Net: 6.0, 7.0

**Describe the bug**
- On which step of the process did you run into an issue: 
VS would be crash after changing "Does the data contain column headers" from "Yes" to "No".

**TestMatrix**
https://testpass.blob.core.windows.net/test-pass-data/wikipedia-detox-250-line-data.tsv

**To Reproduce**
  1. Select Create a new project from the Visual Studio start window.
  2. Choose the C# Console App (.NET Core) project template.
  3. Add model builder by right click on the project.
  4. Select "**Data classification&Value predication&Recommendation&Text classification&Sentence similarity**" scenario.
  5. On Data page, choose the data source. 
  6. Click the "Advanced data options..." link, go to the "Data formatting" tab and then change "Does the data contain column headers" from "Yes" to "No".
  7. VS would be crash after clicking the "Save" button.
  
**Expected behavior**
Changing "Does the data contain column headers" from "Yes" to "No" successfully.

**Gif**
![#2643](https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/dc2a3bbc-e056-40c7-b629-ab7da49de207)

**Additional context**

**Comment by zewditu** [comment] 2023-05-19 18:14
I can not reproduce it.

https://github.com/dotnet/machinelearning-modelbuilder/assets/36615490/519f053c-37ab-44c9-bb47-e73833d96f7b

**Comment by zewditu** [comment] 2023-05-19 19:27
@v-Hailishi  sorry,  I missed the step to set label.

**Comment by luisquintanilla** [comment] 2023-05-22 20:44
Closing since this issue will be fixed at the same time as #2634

**Closed by luisquintanilla** 2023-05-22 20:44 UTC
Labels: Priority:0, Reported by: Test

**Comment by v-Hailishi** [comment] 2023-05-25 08:19
The bug has been fixed on the latest main build 17.16.0.2327401.
<img width="352" alt="image" src="https://github.com/dotnet/machinelearning-modelbuilder/assets/99375895/23557230-d491-47df-990c-b4ee91697cb6">
