### ISSUE TITLE
Unable to locate main() error and Duplicate AssemblyVersion Attribute errors

### ISSUE THREAD

**Issue by dinesarun** [dotnet/machinelearning-modelbuilder#500] opened 2020-02-07 15:46 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Faced error while I run my sample. Resolved it by following this answer - https://stackoverflow.com/a/44502724/2185398 

In addition to that, as there are 2 apps in solution with main() function, it showed the same as error. Resolved this by unloading the "myMLAppML.ConsoleApp" project and remove the same from "myMLApp" project.

**Comment by JakeRadMSFT** [comment] 2020-02-10 19:10
Duplicate of #433

This is because the project is setup in "Project in same folder as Solution". We have a fix for this in the next release.

To work around this until then, ensure the solution (.sln) and project (.csproj) are in separate folders. This is an option when creating the project from scratch.

Alternatively, you can exclude the folders for the generated projects from the project you originally clicked "Add Machine Learning" from. Sorry for the inconvenience!

**Comment by JakeRadMSFT** [comment] 2020-02-10 19:10
Closing issue as duplicate. If the work around doesn't resolve this issue please re-open and provide more details.

**Closed by JakeRadMSFT** 2020-02-10 19:10 UTC
