### ISSUE TITLE
Compile error - NETSdkError

### ISSUE THREAD

**Issue by rufusasterisk** [dotnet/machinelearning-modelbuilder#382] opened 2019-11-22 23:06 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Issue: Program will not compile, throws NETSdkError

Recreation steps - 
Using Visual Studio 2019, I followed the steps of the tutorial until the run phase. Trying to build the console app generates a NETSdkError on line 127 of C:\Program Files\dotnet\sdk\3.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets

The error says the SDK Framework is not compatible with .NET 3.1 - 3.0 or lower should be used.

Setting the project to target .NET 3.0 generates 14 build errors (Duplicate System.Reflection attributes) and 6 warnings from imported type conflicts. The build errors are from conflicts in generated files. Modifying the files doesn't work - they're recreated by the build process.

I feel I'm missing something simple but can't figure out what's wrong

**Comment by beccamc** [comment] 2019-11-25 23:30
Thanks for reporting this problem! We'll take a look.

**Comment by JakeRadMSFT** [comment] 2019-12-04 07:40
Can you share a screenshot of your solution?

**Comment by JakeRadMSFT** [comment] 2019-12-11 21:19
I believe the issue is that the solution and project are in same folder. The tutorial tries to get you to setup the projects to be in sub folders.

If they're in the same folder then things get wacky. We're looking to fix this in an upcoming release. For now you can ensure the projects and solutions are not in the same folder but instead in sub folders (this is the default in VS).

**Comment by JakeRadMSFT** [comment] 2019-12-11 21:21
I believe this is a duplicate of #359

**Comment by JakeRadMSFT** [comment] 2019-12-11 21:22
Resolving as duplicate due to no activity.

**Closed by JakeRadMSFT** 2019-12-11 21:22 UTC
