### ISSUE TITLE
Why don't we make more input output columns?

### ISSUE THREAD

**Issue by mrtrinhvn** [dotnet/machinelearning-modelbuilder#1414] opened 2021-04-21 03:08 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LittleLittleCloud** [comment] 2021-04-21 16:32
Maybe we can! Can you give a tiny example here

**Comment by Mukund-Iyer** [comment] 2021-04-27 19:11
I think @mrtrinhvn is referring to the "Value prediction" scenario in the ML.Net Model Builder which only allows single Column to Predict while all the other columns become Input. @mrtrinhvn wants to have multiple Columns to Predict. Currently, we have one column to predict as shown in image.
![Capturezsd](https://user-images.githubusercontent.com/82875381/116298727-6d091700-a7ba-11eb-9063-771bb1813c1b.PNG)

**Comment by LittleLittleCloud** [comment] 2021-04-28 19:56
Hi @Mukund-Iyer 

I'm not sure if I'm followed. Do you mean something like multi-label classification?

**Comment by Mukund-Iyer** [comment] 2021-04-29 06:05
Yes. I think the OP is asking us to provide solution to a classic multi-output classification problem.

**Comment by beccamc** [comment] 2021-07-15 16:14
I'm closing this, as it's a duplicate of 1510. Please see 1510 for updates on multi-output classification

**Closed** 2021-07-15 23:37 UTC
