### ISSUE TITLE
Loading this assembly would produce a different grant set

### ISSUE THREAD

**Issue by Giri1982** [dotnet/machinelearning-modelbuilder#267] opened 2019-10-05 09:24 UTC
**System Information (please complete the following information):**
 -- Model Builder Version: 16.0.1909.2101
--Visual Studio Version : 2019 16.3.2

**Describe the bug**
Loading this assembly would produce a different grant set from other instances. (Exception from HRESULT: 0x80131401)

**To Reproduce**
Follow the steps mentioned in the below address.
https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/install 

When we click on train an error is thrown.

**Expected behavior**
After model training finishes, go to the Evaluate step.

**Screenshots**
<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/7299289/66253028-13786c00-e780-11e9-9e18-5d036be53829.png">

**Additional context**

**Comment by JakeRadMSFT** [comment] 2019-10-09 07:20
Thanks for reporting this issue! I'm unable to reproduce this but I'll try to track down the cause.

Were you using the dataset from the tutorial -  'wikipedia-detox-250-line-data.tsv'? 
Is the machine 64bit or 32bit?
Do you have another machine to try it out on?

Can you look under %temp%\servicehub\logs and see if there are any logs with ModelBuilder in the file name?

**Comment by JakeRadMSFT** [comment] 2019-10-09 07:20
@AArnott have you seen anything like this? It seems to be happening really early in our attempt to talk to our ServiceHub service.

**Comment by JakeRadMSFT** [comment] 2019-10-09 07:30
Searching the web seems to come up with workarounds but they seem to be SharePoint or Web Related.

@Giri1982 This seems environmental. Can you try installing any pending Windows updates, VS updates, .NET Framework updates, and rebooting? 

Is there anything else different about this machine? Multi-User/Remote Desktop?

**Comment by AArnott** [comment] 2019-10-09 14:07
No, I've never seen that error.

**Comment by JakeRadMSFT** [comment] 2019-10-25 19:33
@Giri1982 closing this issue but please re-open if you hit it consistently.  This should be a very very rare bug to hit.

**Comment by pdrozdowski** [comment] 2019-10-31 08:26
Hi,
I got the same problem.
Only error in log C:\Users\padrozdo\AppData\Local\Temp\servicehub\logs\0340F6B9\ServiceHub.Host.CLR.x86-17220\TestWindow Service Client-hubControllerLookup-17220-ngim0r30-1.log
is:
10/31/2019 09:23:52 Central European Standard Time : Warning : Controller terminated with exit code '21'. Signaling cancellation.

**Comment by LittleLittleCloud** [comment] 2020-06-15 17:52
We are working on a fix(#834 ) for this issue

@Giri1982 @graposo1 Can you help us test that fix when it's ready? It's a rare bug from CLR, and is quite difficult to reproduce.

Please reply to #834 if you want to try that test fix!

**Comment by LittleLittleCloud** [comment] 2020-07-02 17:42
Close due to no response, feel free to re-open it though

**Closed by LittleLittleCloud** 2020-07-02 17:42 UTC
Labels: Customer Reported
