### ISSUE TITLE
Training time only calculated when link clicked

### ISSUE THREAD

**Issue by beccamc** [dotnet/machinelearning-modelbuilder#231] opened 2019-09-12 18:16 UTC
**System Information (please complete the following information):**
 - Model Builder Version: master

**Describe the bug**
The suggested training time is only updated if you click "train" link at the bottom of the page. If you navigate via the left hand menu it stays 10 seconds. 

**To Reproduce**
1. Load large data set
2. Click "Train" on the left hand menu
3. See that the training time is only 10 seconds 

**Expected behavior**
Both navigation options should do the same thing

![wrongTrainTime](https://user-images.githubusercontent.com/9122518/64809740-c8878200-d54e-11e9-802c-a677bb9345b3.gif)

**Comment by JakeRadMSFT** [comment] 2019-09-17 20:52
Duplicate of #189

**Closed** 2019-09-17 20:52 UTC
