### ISSUE TITLE
Error while using Model Builder

### ISSUE THREAD

**Issue by ploverman** [dotnet/machinelearning-modelbuilder#774] opened 2020-05-28 04:16 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

I am running  the tutorial for Model builder on Visual studio community  2019 version 16.6.0 as an administrator,
 and I get a message asking if I want to enable Model Builder.  But Model Builder is enabled. 
[errorPic.docx](https://github.com/dotnet/machinelearning-modelbuilder/files/4693183/errorPic.docx)

**Comment by JakeRadMSFT** [comment] 2020-06-01 23:45
Thanks for your patience! We've fixed this issue in VS 16.6.1 and that went out today. Please update and you should see that this issue has been resolved. If you're stilling having any issues, don't hesitate to reach out again!

Thanks for using Model Builder!

Cheers,
Jake

Duplicate of: #764

**Closed by JakeRadMSFT** 2020-06-01 23:45 UTC
