### ISSUE TITLE
Image Dataset Loader

### ISSUE THREAD

**Issue by justinormont** [dotnet/machinelearning-modelbuilder#802] opened 2020-06-06 10:23 UTC
**Is your feature request related to a problem? Please describe.**
The current dataset loader for the Azure connected mode (and perhaps elsewhere) is difficult to use.

![image](https://user-images.githubusercontent.com/4080826/83940349-9717ac00-a798-11ea-8235-b14c77db44f1.png)

In this dialog, I have to keep drilling down on the path one-by-one. 

**Describe the solution you'd like**
Perhaps we could use a standard file/open dialog? This would allow for my normal interaction style, where I can navigate directly to the folder by pasting it, and it will remember the last folder used.

**Comment by JakeRadMSFT** [comment] 2020-07-06 23:01
Duplicate of #394

**Comment by JakeRadMSFT** [comment] 2020-07-06 23:01
Resolving this issue but I'll move 394 to committed for August. Unfortunately, it's still a low priority.

**Closed by JakeRadMSFT** 2020-07-06 23:02 UTC
