### ISSUE TITLE
[Azure] - Create New Experiment Subscription - Unable to see my subscriptions

### ISSUE THREAD

**Issue by wahyuen** [dotnet/machinelearning-modelbuilder#1025] opened 2020-09-30 01:46 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.0.2046002
 - Visual Studio Version 16.7.4

**Describe the bug**
- On which step of the process did you run into an issue: Attempt to setup environment for object detection in model builder
- Clear description of the problem: I should expect to see all the Subscriptions that I have access to across multiple tenants, currently see none.

**To Reproduce**
1. Right click project, Add > Machine Learning
2. Select Object detection scenario
3. Select Set up workspace

**Expected behavior**
A list of all the subscriptions that I have access to

**Screenshots**
![image](https://user-images.githubusercontent.com/4549796/94634075-a8656500-0301-11eb-95f8-4ba67eeb0e28.png)

An example of my 'Publish' interface, where it can correctly see my Subscriptions
![image](https://user-images.githubusercontent.com/4549796/94634150-dba7f400-0301-11eb-8811-8da65ee481b1.png)

**Comment by beccamc** [comment] 2020-09-30 15:31
@wahyuen Sorry you ran into this problem! Can you try clicking on your user profile and make sure you are logged in. The process can be a little touchy to make sure you're logged in. 

![image](https://user-images.githubusercontent.com/9122518/94706637-0f861800-0308-11eb-9669-79f7f4c97a6c.png)

**Comment by wahyuen** [comment] 2020-09-30 15:55
@beccamc definately logged in....even tried to remove the account and re-add it...same issue. Is it possible this is something to do with guest accounts (something we run into regularly as we are across multiple tenants). Definately seems to work fine in terms of seeing other subscriptions via things such as the 'Publish...' interface

**Comment by wahyuen** [comment] 2020-11-12 01:37
@beccamc Hi! Just wanted to check in to see if there was perhaps a fix or a workaround? Still completely blocked with the issue even with the latest VS2019 16.8 release

**Comment by beccamc** [comment] 2020-11-13 20:23
@wahyuen Sorry for the delay and thank you for the additional info. I've found the cause of the problem. If you have multiple tenants we're pulling the subscriptions from only one (I think it's the first one alphabetically). I'm guessing one of your tenants doesn't have subscriptions? I'm working on a fix to pull all tenants like elsewhere in the product.

**Comment by wahyuen** [comment] 2020-11-14 00:23
@beccamc No worries! Thanks for responding! Its a relatively common scenario for us since we manage applications across quite a few customer tenants! Looking forward to the fix! Do let us know if you need a hand testing any of this!

**Comment by wahyuen** [comment] 2021-02-05 07:27
@beccamc Just wanted to check if this fix ever made it out? I saw it linked to the November hotfix but it looks like its still an issue as of today in VS (5th Feb 2021)

Extension details here:
![image](https://user-images.githubusercontent.com/4549796/107002685-91121900-67c6-11eb-86dd-d38656ad3ee9.png)

**Comment by beccamc** [comment] 2021-02-25 17:23
@wahyuen I'm sorry. There is no excuse for the length of time resolving this issue. I had a build ready for release in November, but it had a problem and in the holiday rush it got lost. 

We have completely re-written the way Model Builder loads (it's now config based and instances can be reloaded). We have a preview build releasing next Wednesday, and the fix will be included in that. I anticipate a regular release in mid March. 

Thank you very much for your patience. We are a small team, and unfortunately things slip through the cracks. You've been really understanding and I do want to resolve this for you ASAP.

**Comment by wahyuen** [comment] 2021-02-26 00:51
@beccamc No worries...completely understand things can get lost :)

Thanks for taking the time to respond and I look forward to the release in March :)

**Comment by beccamc** [comment] 2021-03-05 18:13
XiaoYun valided this in the 2/26 bash!
![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/be793e34-850d-45b4-a7c2-0bb13099da23)

**Closed** 2021-03-05 19:25 UTC
Labels: Customer Reported
