### ISSUE TITLE
Object Detection Feature

### ISSUE THREAD

**Issue by Ezeji** [dotnet/machinelearning-modelbuilder#1023] opened 2020-09-29 20:53 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.2.0.2046002
 - Visual Studio Version: 16.7.4

**Describe the bug**
- On which step of the process did you run into an issue: I ran into an issue while trying to setup a workspace for my custom model training.
- Clear description of the problem: While creating a workspace, the tool enforces only Enterprise grade workspaces which Azure no longer supports from September therefore meaning all creating new workspaces only have access to a Basic grade owing to the new development with Azure Machine Learning. it therefore implies that persons that can perform object detection experiments must have had an Enterprise grade workspace prior to this release.

**To Reproduce**
1. Go to Model Builder.
2. Click on Object Detection Scenario.
3. Click on Workspace in Environment and follow the prompt.
4. Click on create to generate a workspace after which the error is displayed. 

**Expected behavior**
A clear and concise description of what you expected to happen: So I was expecting that Model Builder would sync with the new development with Azure Machine Learning by either allowing ability to create Enterprise and Basic grades workspaces or only Basic grade workspace following the announcement from Microsoft on migrating totally to Basic grade workspace which is implemented to be assigned automatically when using the portal to create a workspace.

**Screenshots**

**Additional context**

**Comment by beccamc** [comment] 2020-09-29 21:57
@Ezeji Sorry you've run into this problem! This is a duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/1020. 

I have a fix and am working on getting it released. Please follow 1020 for updates. Thanks!

**Comment by Ezeji** [comment] 2020-09-30 22:18
@beccamc thanks alot for your response, I have checked out the duplicate and would be anticipating the release.

You guys are doing a great Job.

**Closed** 2020-10-26 22:40 UTC
