### ISSUE TITLE
Data page: Data loading issues

### ISSUE THREAD

**Issue by romalpani** [dotnet/machinelearning-modelbuilder#1275] opened 2021-02-23 23:10 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
1. When I first uploaded file data (Taxifare) the data preview loaded almost instantly but VS threw a Gold bar message suggesting to disable the extension.
![image](https://user-images.githubusercontent.com/48927690/108920280-3f9cc300-75e9-11eb-985f-3bed25a0e1df.png)

2. I went back and tried to add the same file again (Taxifare). This time, there was a spinner in the middle of the screen.
 
![image](https://user-images.githubusercontent.com/48927690/108920260-37448800-75e9-11eb-8642-9d667c500428.png)

**To Reproduce**
1. Go to Text classification / Value prediction
2. Env page: Select local option
3. Data page: Use local file (TaxiFare) to upload.

**Expected behavior**
1. From a functional perspective, customer should not see the gold bar message. Instead, if we can detect any potential issue with the data, we should show a message on the data page itself. We will need to hash out the experience for this edge case scenario.

2. The spinner that shows up in the center is not the right spinner and not the right place. 
This will need a design mock-up. Let's add this to our to-do list.

**Screenshots**

**Additional context**

**Comment by beccamc** [comment] 2021-04-15 19:28
This is a duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/1374 and

**Closed** 2021-04-15 19:32 UTC
Labels: Bug Bash, Priority:1
