### ISSUE TITLE
Error with Azure training

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#497] opened 2020-02-06 23:25 UTC
Not sure what this one is about:
![image](https://user-images.githubusercontent.com/10437687/73987275-a7a43c80-48f4-11ea-8ef6-a9454e45c330.png)

I went through like normal and was able to select workspace, compute, etc. like normal.

Also -- would it be possible when a user select "report issue" to send them to an already filled out template of a bug with their version of VS, Model Builder, and also the error message?

**Comment by JakeRadMSFT** [comment] 2020-02-10 19:07
Not sure about the root cause but we should add retry logic. This seems like an intermittent error.

**Comment by beccamc** [comment] 2020-03-05 20:06
@JakeRadMSFT Xiaoyun added retry logic right? Can this be closed?

**Comment by beccamc** [comment] 2020-03-10 00:40
Retries have been implemented. Closing this.

**Closed by beccamc** 2020-03-10 00:40 UTC
Labels: Enhancement
