### ISSUE TITLE
Trouble instaling ML.NET Model Builder package

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#110] opened 2019-06-18 18:44 UTC
Customer reported the following issue on SO https://stackoverflow.com/questions/56306765/trouble-instaling-ml-net-model-builder-package

I´m trying to install ML.NET 1.0 package into Visual Studio 2017, so I can practice the ML.NET Model Builder,

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by greazer** [comment] 2019-06-18 18:55
Dupe of #95

**Closed by greazer** 2019-06-18 18:55 UTC
Labels: Customer Reported, Duplicate
