### ISSUE TITLE
Cannot see any server in server list

### ISSUE THREAD

**Issue by ddemland** [dotnet/machinelearning-modelbuilder#986] opened 2020-09-02 18:48 UTC
**System Information (please complete the following information):**
 - Model Builder Version: Date Installed: 9/1/2020 Version: 16.1.1.2041102
 - Visual Studio Version: Microsoft Visual Studio Professional 2019 Version 16.7.2

**Describe the bug**
On the Choose Data Source dialog the list of servers is never populated.

**To Reproduce**
When I add a machine learning value prediction, I select Local CPU environment, then I select SQL Server option for input. When I select the <SQL datasource> option I select Microsoft SQL Server option:

![image](https://user-images.githubusercontent.com/67738/92023455-a663b280-ed11-11ea-9e87-f065cbd5cb2d.png)

The Connection properties show no SQL Servers:

![image](https://user-images.githubusercontent.com/67738/92023567-cc895280-ed11-11ea-896a-a7a6276043f2.png)

When I select the Refresh option it still finds no servers. However, when I enter the server IP, the SQL Server Authentication, I can select the table. I can also select Test Connection and I get a Test connection succeeded message.

![image](https://user-images.githubusercontent.com/67738/92023642-e165e600-ed11-11ea-8472-83ba31289bae.png)

If there is no IP entered and I select Refresh, I get the message that a list of servers are being retrieved:

![image](https://user-images.githubusercontent.com/67738/92023728-02c6d200-ed12-11ea-9300-81489c52d067.png)

Once this message goes away there are still no servers listed even I select the drop down.

![image](https://user-images.githubusercontent.com/67738/92023756-0bb7a380-ed12-11ea-9624-2c0497962335.png)

Should I not see the server in the list?

**Comment by LittleLittleCloud** [comment] 2020-09-09 20:56
Well, since in the second attempt, your server name is empty. So SQL server connection service won't know which server to connect to and therefore no table/server will be listed.

**Comment by ddemland** [comment] 2020-09-11 16:21
I think you missed the point, if you look above, after selecting refresh there is a dialog that shows "Please wait while we retrieve the list of servers ...". When this dialog is closed there are no servers in the list. Yet if you look above that I have connected to a server by giving the IP and it works. This proves there is a server on the network and the refresh fails to find that server.

This is the issue: at no time is a live SQL Server put into this dropdown. Either there is an issue with the server discovery, or the dialog should be changed to force the user to input the server IP/host. It is very confusing to a user to have a dropdown and refresh button that does not work.

**Comment by LittleLittleCloud** [comment] 2020-09-14 18:13
Oh I see your point now, The sql connect tool is from Visual studio, and model builder simply calls it from VS SDK. (Tools -> Connect to Database -> Microsoft SQL Server). Why the team which owns this tool puts a dropdown list and refresh button that doesn't work is unclear though, they may miss that, or they might have a specific reason to design that we don't know. We will deliver your feedback to them to find the answer

**Comment by ning51** [comment] 2020-10-26 16:44
This is most likely by design. The server list (which will be repopulated if you click the Refresh button) includes all available instances of SQL Server _**within the local network**_. The list is returned by [System.Data.Sql.SqlDataSourceEnumerator.Instance.GetDataSources()](https://docs.microsoft.com/en-us/dotnet/api/system.data.sql.sqldatasourceenumerator.getdatasources?view=netframework-4.7.2). The list may be empty if there is not SQL Server instance in your local network.

**Comment by beccamc** [comment] 2020-11-06 17:54
@ddemland Does the response above explain the difference?

**Comment by beccamc** [comment] 2020-11-12 17:20
Closing this. If the problem persists please ping me an re-open the issue. Thanks!

**Closed by beccamc** 2020-11-12 17:20 UTC
Labels: Customer Reported
