### ISSUE TITLE
Weird ML Example Behaviour using VS2019

### ISSUE THREAD

**Issue by CodeGetter** [dotnet/machinelearning-modelbuilder#503] opened 2020-02-09 19:57 UTC
Using the tutorial https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Following the steps the example compiles with errors:

1. First build 14 errors (see attached)
2. Add code to project TestAppCore:Program.cs as shown in the Consume your model step at lines 11 and 14
3. Rebuild with 1 error (see attached)

> Error CS2001 Source file 'E:\DotNet WorkSpace\VS 2019 Projects\C#\TestAppCore\TestAppCoreML.ConsoleApp\obj\Debug\netcoreapp2.1\TestAppCoreML.ConsoleApp.AssemblyInfo.cs' could not be found.	TestAppCore	E:\DotNet WorkSpace\VS 2019 Projects\C#\TestAppCore\CSC	1

> 
4.  Clean Solution
5. Build with 7 errors ((see attached)

Decided to restart example using a different approach

6. Created an empty solution
7. Added a Console App (.Net Core)
8. Selected Machine Learning as an addition to the Console Project.
9. Repeated above step 2.
10. Build and execution was successful with output identical to that shown in the Consume your model step. (see attached)

![ML Build 1](https://user-images.githubusercontent.com/6624553/74108741-44750d00-4b75-11ea-81ec-d1dea6f6652b.jpg)

![ML ReBuild](https://user-images.githubusercontent.com/6624553/74108743-450da380-4b75-11ea-82e7-5fd920d3be3a.jpg)

![Explorer](https://user-images.githubusercontent.com/6624553/74108806-b3526600-4b75-11ea-947c-fa128c22c203.jpg)

![ML Build 2](https://user-images.githubusercontent.com/6624553/74108742-44750d00-4b75-11ea-9db7-b2a574591cd2.jpg)

![Successful Build](https://user-images.githubusercontent.com/6624553/74108744-450da380-4b75-11ea-8ad4-dc08a39eef69.jpg)

![Console Msg](https://user-images.githubusercontent.com/6624553/74108739-3de69580-4b75-11ea-9634-bcd05403e04c.jpg)

No idea as to why there should be a difference; errors using the first method and no errors using the second method.
Hopefully this feedback proves useful.

**Comment by JakeRadMSFT** [comment] 2020-02-10 19:19
Duplicate of #433

This is because the project is setup in "Project in same folder as Solution". We have a fix for this in the next release.

To work around this until then, ensure the solution (.sln) and project (.csproj) are in separate folders. This is an option when creating the project from scratch.

Alternatively, you can exclude the folders for the generated projects from the project you originally clicked "Add Machine Learning" from. Sorry for the inconvenience!

**Closed by JakeRadMSFT** 2020-02-10 19:19 UTC
