### ISSUE TITLE
Severity	Code	Description	Project	File	Line	Suppression State Error	CS0579	Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute	MLNetC	C:\Users\urrehmsf\Documents\Visual Studio 2019\MyProjects\MLNetC\MLNetCML.Model\obj\Debug\netstandard2.0\MLNetCML.Model.AssemblyInfo.cs	15	Active

### ISSUE THREAD

**Issue by Syedfaizanurrehman** [dotnet/machinelearning-modelbuilder#484] opened 2020-02-04 19:04 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment] 2020-02-10 18:44
Duplicate of #433.

Copied from #433:

This is because the project is setup in "Project in same folder as Solution". We have a fix for this in the next release.

To work around this until then, ensure the solution (.sln) and project (.csproj) are in separate folders. This is an option when creating the project from scratch.

Alternatively, you can exclude the folders for the generated projects from the project you originally clicked "Add Machine Learning" from. Sorry for the inconvenience!

**Comment by JakeRadMSFT** [comment] 2020-02-10 18:45
Closing this issue, if the work around doesn't resolve the issue please re-open and provide more context.

**Closed by JakeRadMSFT** 2020-02-10 18:45 UTC
