### ISSUE TITLE
Getting Invocation Error while trying to add Machine Learning

### ISSUE THREAD

**Issue by pronobeshm** [dotnet/machinelearning-modelbuilder#582] opened 2020-03-17 11:10 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/create
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.
![ML Exception](https://user-images.githubusercontent.com/49061295/76850676-e4f1d780-686d-11ea-9bda-7e8acf101ef2.jpg)

Getting attached exception while I am trying to add Machine Learning

**Comment by LittleLittleCloud** [comment] 2020-03-24 23:32
Could you provide your Visual Studio's version? (Help -> About Microsoft Visual Studio)

**Comment by pronobeshm** [comment] 2020-03-25 08:35
Thanks for your reply.
My Visual Studio Version 2017 and it is community edition.

**Comment by beccamc** [comment] 2020-04-14 18:19
Thanks for reporting @pronobeshm! I'm trying to reproduce this problem. I've used VS 2017 Community 
![image](https://user-images.githubusercontent.com/9122518/79259474-a259f580-7e41-11ea-82da-720c39bf308a.png)

I am able to add Machine Learning...
![image](https://user-images.githubusercontent.com/9122518/79259545-bc93d380-7e41-11ea-801c-95e7f44f5902.png)

Can you please update to the latest version of VS and Model Builder?

**Comment by beccamc** [comment] 2020-04-20 17:27
@pronobeshm Friendly ping, is this still not working?

**Comment by beccamc** [comment] 2020-04-23 18:20
@pronobeshm I can't reproduce the problem so I am closing this issue. If you're still experiencing this problem please let me know and we can re-open. Thanks for reporting!

**Closed by beccamc** 2020-04-23 18:20 UTC
Labels: Bug, Customer Reported
