### ISSUE TITLE
Model Builder error occurs on the process of model builder for Azure.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1406] opened 2021-04-20 02:41 UTC
**System Information (please complete the following information):**
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.0.2115505
- Microsoft Visual Studio Enterprise 2019: 16.9.3
- .Net: 5.0.201

**To Reproduce**
1. Create new console app with .Net 5.0;
2. Add model builder by right click on the project;
3. Select "Object detection" scenario, 
4. Jump to Environment page with prompting the Model Builder error dialog;
4. Close the error dialog, select "Azure" and set up workspace on Environment page;
5. Go to Data page, input the JSON file with image (labeled and exported by Vott);
6. Prompt the Model Builder error dialog;
7. Close the error dialog and click start train on Train page;
8. Trained successfully.

**Expected behavior**
Even if the error does not affect the success of train, don't want to prompt any error dialog during the process of model builder.

**Screenshots**
Error dialog:
![image](https://user-images.githubusercontent.com/81727020/115327903-5b27e280-a1c2-11eb-9621-7f494258f4d5.png)

Trained successfully：
![image](https://user-images.githubusercontent.com/81727020/115328374-1badc600-a1c3-11eb-9cc9-aa1fcfec6fed.png)

**Additional context**
1. Tutorials reference:
https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/object-detection-model-builder
2. This error dialog also prompts if reopen the model builder.

**Comment by vzhuqin** [comment] 2021-05-14 09:39
This issue still occurs on Main branch: 
https://privategallery.blob.core.windows.net/gallery/refs/heads/main/atom.xml
- Windows 10 Enterprise, Version 20H2
- ML.Net Model Builder (Preview): 16.5.24.2125801
- Microsoft Visual Studio Enterprise 2019: 16.9.4
- .Net: 5.0.202

**Comment by beccamc** [comment] 2021-05-19 16:42
This seems to be a duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/1412. The problem is if one of your VS identities isn't valid for Azure, we throw an exception. The stack trace here is the same as 1412. 

> System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
>    at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
>    at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.MsalNetworkServicesImpl.AcquireTokenSilentAsync(string resource, string tenant, UserIdentifier userId, CancellationToken cancellationToken)
>    at void Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
>    at async Task<AuthenticationInfo> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireAuthenticationInfoSilentAsync(string resource, string tenantId, Account account, CancellationToken cancellationToken)
>    at async Task<AccessTokenResult> Microsoft.Developer.IdentityService.AccountProvider.AadAccountProviderService.AcquireTokenAsync(string resource, string tenantId, Account account)
>    at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<GetUserTokenAsync>d__6.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 103
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.ML.ModelBuilder.AzureAttach.UserAuthorizationManager.<TryReloadAzureUserAsync>d__5.MoveNext() in C:\Repos\machinelearning-tools\src\Microsoft.ML.ModelBuilder\AzureAttach\UserAuthorizationManager.cs:line 70

Closing this as a duplicate.

**Closed by beccamc** 2021-05-19 16:42 UTC
Labels: Test Pass
