### ISSUE TITLE
Cannot compile Web API project TaxiFare_API

### ISSUE THREAD

**Issue by ekleiman22** [dotnet/machinelearning-modelbuilder#1784] opened 2021-09-14 09:47 UTC
**System Information (please complete the following information):**
 - Model Builder or CLI Version: 16.7.3.2143002
 - Visual Studio Version (if applicable): 2019, Version 16.11.2

**Describe the bug**
- On which page of the tutorial did you run into an issue [(URL):](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/predict-prices-with-model-builder?WT.mc_id=dotnet-35129-website)
- Clear description of the problem: After finishing of project **TaxiFarePrediction** I added to it Web API project **TaxiFare_API**. When I tried to run it I got the following error message:
- **Error	NETSDK1045	The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.	TaxiFare_API	C:\Program Files\dotnet\sdk\5.0.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	141**
It was strange because project TaxiFarePrediction  was under Net5.0 and I don't have Net6.0. So I changed in TaxiFare_API.csproj the value of TargetFramework to net5.0. But after that I got the following error message:
**Error	CS0103	The name 'WebApplication' does not exist in the current context ...Program.cs	9**
After that all Visual Studio hanged.
So I need to know how it could be fixed?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by zewditu** [comment] 2021-09-14 15:46
@ekleiman22 sorry for hitting this issue. The issue is known  https://github.com/dotnet/machinelearning-modelbuilder/issues/1664 and I will be fixed in the September release of the Model Builder.

**Closed by zewditu** 2021-09-14 15:46 UTC
Labels: GS Tutorial
