### ISSUE TITLE
Error while training 

### ISSUE THREAD

**Issue by SH2015** [dotnet/machinelearning-modelbuilder#660] opened 2020-04-08 04:17 UTC
**System Information (please complete the following information):**
 - Model Builder Version: Latest as of today (2020-04-08 ) 
 - Visual Studio Version : 2019 

**Describe the bug**
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AutoMLExperiment`3.<ExecuteAsync>d__23.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\Experiments\AutoMLExperiment.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ML.ModelBuilder.AutoMLEngine.<StartTrainingAsync>d__28.MoveNext() in E:\A\_work\1326\s\Microsoft.ML.ModelBuilder.AutoMLService\AutoMLEngineService\AutoMLEngine.cs:line 134
**To Reproduce**
Press training after setting the data 

**Expected behavior**

**Screenshots**

**Additional context**
Training Data : 

Days | Cases
-- | --
1 | 101
2 | 110
3 | 116
4 | 124
5 | 154
6 | 164
7 | 192
8 | 208
9 | 214
10 | 233
11 | 266
12 | 316
13 | 346
14 | 382
15 | 458
16 | 506
17 | 547
18 | 630
19 | 694
20 | 728
21 | 772
22 | 820
23 | 878
24 | 961
25 | 1031
26 | 1122
27 |  
28 |  
29 |  
30 |  
  |  
  |

**Comment by LittleLittleCloud** [comment] 2020-04-08 17:24
What's your training scenario (Is that regression?) label and error message

**Comment by SH2015** [comment] 2020-04-09 01:04
> What's your training scenario (Is that regression?) label and error message

It is regression, the dataset is very simple

**Comment by beccamc** [comment] 2020-04-15 20:34
@SH2015 It looks like we're running out of time training the model? There are two reasons for this. 30 rows of data is a fairly small sample and difficult to train against (ML.Net will split the set into 80% training and 20% testing). Additionally, it looks like the scenario you're trying to accomplish is more closely aligned to forecasting - predict future cases based on historical data.

Unfortunately we don't support forecasting in Model Builder yet. You can check out this [tutorial ](https://docs.microsoft.com/en-us/dotnet/machine-learning/tutorials/time-series-demand-forecasting) in the ML.NET docs. If you want to stay in Model Builder you could try adding the additional data to your dataset and see if that is enough data to train on. I'm guessing you won't get a very accurate model since you're really looking for a forecasting model.

Let me know if I've misinterpreted your dataset and scenario. I'll pass along to our PM a request for forecasting in Model Builder.

**Comment by beccamc** [comment] 2020-04-21 20:36
Closing this issue. @SH2015 please let us know if we can help with anything else. Thanks for reporting!

**Closed by beccamc** 2020-04-21 20:36 UTC
Labels: Customer Reported

**Comment by SH2015** [comment] 2020-04-26 20:24
@beccamc Any plan to include time-series forecasts in Model Builder? there are too many applications in business for time-series analysis

**Comment by beccamc** [comment] 2020-04-28 20:22
@SH2015 We are planning to add this Model Builder but I'm not sure of the timeline. We're tracking this work in Issue #609. I've added your comments to that issue and pinged our PM. If you want more info, or want to provide additional feedback please checkout 609. Thanks!
