### ISSUE TITLE
Add ML.NET 1.2 NuGet package to the user's app instead of 1.0 and update the text on the Code step

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#152] opened 2019-07-10 21:15 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version:

**Describe the bug**
Update to 1.2 Nuget package and remove the text which asks the user to install the NuGet package

**To Reproduce**
1. Complete 'SentimentAnalysis'
2. Click on 'Add Projects' in code screen

**Expected behavior**
ML.NET 1.2 NuGet package should be added instead of ML.NET 1.0

**Screenshots**
![image1](https://user-images.githubusercontent.com/1132652/61005644-6f685b80-a31d-11e9-96ba-a4cc194f639c.PNG)

**Additional context**

**Comment by JakeRadMSFT** [comment] 2019-07-10 22:50
Duplicate of #157

**Closed by JakeRadMSFT** 2019-07-10 22:50 UTC
