### ISSUE TITLE
Training should fail if error

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#1291] opened 2021-02-25 20:54 UTC
Follow up to #1290

After I got the training error, it actually said training was completed and let me move on to Evaluate:
![image](https://user-images.githubusercontent.com/10437687/109215816-8cf36e80-7768-11eb-92de-59a1e8bb9889.png)

Training should fail if there is an error and not let me move on.

**Comment by beccamc** [comment] 2021-04-14 21:29
I can't reproduce this. Closing. I'll re-open if I see it again (during the error management work I can catch it if it happens again) 

![image.png](https://images.zenhubusercontent.com/5d55c3d68fac840001314eaa/671eb761-a1fe-4390-b602-ce3edd0610a2)

**Closed by beccamc** 2021-04-14 21:29 UTC
Labels: Bug Bash
