### ISSUE TITLE
GPU Service not found. Falling back to CPU AutoML Service.

### ISSUE THREAD

**Issue by weixinshzf** [dotnet/machinelearning-modelbuilder#881] opened 2020-07-05 08:56 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Tire-Li** [comment] 2020-07-05 11:49
**System Information:**
Model Builder Version: 16.1.0 & 16.1.1
Visual Studio Version : 16.6.3
 
**Dug description:**
Can not finish training and "Service.Host.CLR*64.exe" crash down.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/38813219/86531835-31355600-bef7-11ea-8ecb-5bc9e182caee.JPG)

**Additional context**
I had try to training data at both version 16.1.0 & 16.1.1

**Comment by LittleLittleCloud** [comment] 2020-07-06 17:11
Seems to be a dup of #833 #267

We have a fix(#834 ) for this issue, and it will be released soon.

Can you help us test that fix when it's ready? It's a rare bug from CLR, and is quite difficult to reproduce.

Please reply to #834 if you want to try that test fix!

**Comment by LittleLittleCloud** [comment] 2020-07-13 17:40
Close due to no response, feel free to reopen it if you still have the problem

**Closed by LittleLittleCloud** 2020-07-13 17:40 UTC
Labels: Customer Reported
