### ISSUE TITLE
Regression (price prediction) tutorial dataset is only formatted for US/UK culture

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#149] opened 2019-07-10 21:03 UTC
**System Information (please complete the following information):**
 - Model Builder Version: July Release (latest mlnet CLI)
 - Visual Studio Version: Any
 - OS Culture: Finnish (suomi)

**Describe the bug**
Our price prediction (regression) dataset has numbers that are formatted for the US/UK culture. For US/UK English, the decimal separator is `.` character, while for other countries it's `,`. Since the dataset has numbers like 17.5, the mlnet CLI (and AutoML) believes those columns to be strings, not numbers.

**To Reproduce**
1. Change OS Regional format to Finnish (download the language pack called "suomi")
![Screenshot (6)](https://user-images.githubusercontent.com/779479/61004396-ce78a100-a31a-11e9-9f9b-520147eee80f.png)
2. Run Model Builder or mlnet CLI on the [taxi fare dataset](https://github.com/dotnet-machinelearning/mlnet-private-preview/blob/master/CLI/samples/Regression-Taxi-Fare/taxi-fare-train.csv), using the price prediction (regression) task. Use fare_amount as the column to predict

**Expected behavior**
A model should be trained for the dataset.

**Actual behavior**
Training fails with the following error:
```
Exception occured while exploring pipelines:
Provided label column 'fare_amount' was of type String, but only type Single is allowed.
```

**Additional context**
In the past, this was not an issue. AutoML/CLI did not take into account the user's OS culture when reading the file. Now that it parses the file with the user's culture, it doesn't recognize the US formatted datasets as numeric.

**Comment by rustd** [comment] 2019-07-12 17:50
Does the FX (ML.NET and API) support this scenario? @justinormont

**Comment by justinormont** [comment] 2019-07-12 20:01
It should have been fixed in the CLI & AutoML API; though perhaps we missed something. Has the Model Builder updated to 0.14.0 of the mlnet NuGet?

@srsaggam: Can you investigate if the user issue is still reproducible?

**Comment by srsaggam** [comment] 2019-07-12 21:40
Looks like the PR which fixes this issue has not been merged.
https://github.com/dotnet/machinelearning/pull/3731

**Comment by justinormont** [comment] 2019-07-13 07:16
@srsaggam: thanks for closing on the PR. @rustd, @tbombach: fix is part of the next release (0.15.0).

**Comment by beccamc** [comment] 2020-01-22 19:09
@LittleLittleCloud Did this not work when you validated it?

**Comment by beccamc** [comment] 2020-02-26 01:49
Validated with Spain language config (also uses , for decimal point)

**Closed** 2020-02-26 01:50 UTC
