### ISSUE TITLE
Basic references are missing like System.Console, System.String

### ISSUE THREAD

**Issue by rustd** [dotnet/machinelearning-modelbuilder#91] opened 2019-06-03 21:09 UTC
Customer reported issue : https://github.com/dotnet/machinelearning-samples/issues/452

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tbombach** [comment] 2019-06-11 22:36
Duplicate of #65

**Closed by tbombach** 2019-06-11 22:36 UTC
Labels: Customer Reported, P1
