### ISSUE TITLE
Display incorrect evaluation metrics on Train and Evaluate pages for Multiclass classification.

### ISSUE THREAD

**Issue by vzhuqin** [dotnet/machinelearning-modelbuilder#1876] opened 2021-10-27 06:52 UTC
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog): 16.9.1.2152702
 - Microsoft Visual Studio Enterprise 2019: 16.11.5

**Describe the bug**
- On which step of the process did you run into an issue: Train and Evaluate pages
- Clear description of the problem: the evaluation metrics should be MicroAccuracy, but display accuracy on Train and Evaluate pages.

**To Reproduce**
1. Select Create a new project from the Visual Studio 2019 start window;
2. Choose the C# Console App (.NET Core) project template with .Net 5.0;
3. Add model builder by right click on the project;
4. Select Data classification and input the [data](https://github.com/dotnet/machinelearning-samples/raw/main/samples/modelbuilder/MulticlassClassification_RestaurantViolations/RestaurantScores.zip);
5. Complete the training, see that: The evaluation metric it displays on the train and evaluate pages is accuracy. 

**Expected behavior**
The evaluation metric should be displayed MicroAccuracy on the train and evaluate pages.

**Screenshots**
![image](https://user-images.githubusercontent.com/81727020/139014445-5298ac68-1fdb-4ddb-b1a6-e3680c08a13e.png)
![image](https://user-images.githubusercontent.com/81727020/139014515-493aa219-e51d-42ae-81e9-8d159c9ccebf.png)

**Comment by beccamc** [comment] 2021-11-04 19:50
If we're adding additional metrics we need to use the right names. The current experience is by design. We need to reconsider this when we add additional metrics.

**Comment by briacht** [comment] 2021-11-09 16:58
I think it's fine to keep Accuracy for now. We can revisit once we add option for more optimizing metrics

**Comment by beccamc** [comment] 2021-11-09 17:00
@briacht do you think we can close this for now?

**Comment by briacht** [comment] 2021-11-09 17:05
Yep

**Closed** 2021-11-09 17:39 UTC
Labels: Priority:2, Test Team
