### ISSUE TITLE
Training cancelled error

### ISSUE THREAD

**Issue by lennieharvey** [dotnet/machinelearning-modelbuilder#883] opened 2020-07-06 14:47 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

I'm using Windows 10 Enterprise V1803 - OS Build 17134.1550
Visual Studio Professional 2019 V16.6.3

Tried with versions 16.2.0.2026302 & 16.1.0.2027905 of ModelBuilder

So stepping through the tutorial, I got to the train page in the wizard and when I hit the train button I get this:

GPU Service not found. Falling back to CPU AutoML Service.
Training cancelled

Then if I try train again I just get the Training cancelled message

**Comment by LittleLittleCloud** [comment] 2020-07-06 17:11
Seems to be a dup of #833 #267

We have a fix(#834 ) for this issue, and it will be released soon.

Can you help us test that fix when it's ready? It's a rare bug from CLR, and is quite difficult to reproduce.

Please reply to #834 if you want to try that test fix!

**Comment by LittleLittleCloud** [comment] 2020-07-13 17:41
Close due to no response, feel free to reopen it if you still have the problem

**Closed by LittleLittleCloud** 2020-07-13 17:41 UTC
Labels: Customer Reported

**Comment by lennieharvey** [comment] 2020-07-14 16:45
Fix on #834 fixed this for me
