### ISSUE TITLE
After generating code, updating user's project to reference new projects

### ISSUE THREAD

**Issue by tbombach** [dotnet/machinelearning-modelbuilder#14] opened 2019-04-29 20:21 UTC

**Comment by JakeRadMSFT** [comment] 2019-05-24 18:44
Adding Nuget:https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio

**Comment by rustd** [comment] 2019-06-03 18:17
Duplicate of #76

**Closed by rustd** 2019-06-03 18:17 UTC
Labels: Need Details, Needs PM
