### ISSUE TITLE
visual studio 2022 and ML.NET extension doesn't work

### ISSUE THREAD

**Issue by JohnMahanDavis** [dotnet/machinelearning-modelbuilder#2232] opened 2022-08-28 18:46 UTC
**Model Builder Version**: 16.13.10.2241902
**Visual Studion Version**: 17.3.2

**Bug description**
I am not able to start the **Machine Learning Model**.  When I try to build a ML learning model as described in the animation on the following Microsoft website ...  https://dotnet.microsoft.com/en-us/apps/machinelearning-ai/ml-dotnet/model-builder  ... I am **not** able to reproduce the expected result.   

**Steps to Reproduce**
1. First I try to add a new Machine Learning Model to my solution by right clicking on the solution, then selecting **Add** from the pop up menu, then selecting **Machine Learning Model ...** from the flyout menu, as shown below:
![image](https://user-images.githubusercontent.com/20384698/187088370-49cf4676-dad7-4b66-a699-4e95d5991b66.png)

After selecting **Add>> Machine Learning Model ...**, I am presented with the following window 

![image](https://user-images.githubusercontent.com/20384698/187089093-18455d21-0bf7-4a42-a3cb-f4b458026461.png)

At this point I do not know how to proceed to get to the **Machine Learning Model**.  Have I made a mistake, or is there a software issue?

2. _Thanks for reporting!_

**Expected Experience**
After choosing **Add>> Machine Learning Model ...,** I was hoping to see this tab displayed 
![image](https://user-images.githubusercontent.com/20384698/187088751-47f26109-2a15-48c5-b251-f73f5df0422e.png)

**Actual Experience**
But instead,  I was presented with this dialog window ... 
![image](https://user-images.githubusercontent.com/20384698/187089818-c41a7430-8f8c-48bf-b656-7713cfe10b75.png)

**Additional Context**
I had previously updated to the latest available version of Visual Studio 2022.  I also went to the Extensions menu to ensure that the latest version of the ML.Net Model Builder 2022 was installed as shown here ,,, 
![image](https://user-images.githubusercontent.com/20384698/187089721-156f1fe2-c6ec-4eb3-8900-26eaff158c98.png)

I love the concept presented on the MS ML website ( https://dotnet.microsoft.com/en-us/apps/machinelearning-ai/ml-dotnet/model-builder ), but am very  disappointed that I am unable to make it work.  I would really love to know what I can do to participate in this great new approach to ML in Visual Studio.

**Comment by beccamc** [comment] 2022-08-29 19:53
Sorry this isn't working! You aren't missing anything, it looks like our file type isn't available for some reason. 

@v-Hailishi Can you try to reproduce the above problem on Visual Studion Version: 17.3.2?

**Comment by JohnMahanDavis** [comment] 2022-08-29 22:31
The app that I had the problem with is a C# **UWP** app.  I continued to research the problem and was able to to get the ML.Net Model Builder to work by using the tutorial described on this page ... https://dotnet.microsoft.com/en-us/learn/ml-dotnet/get-started-tutorial/create .  One key difference is the app that worked is a C# **Console App** instead of a C# UWP app.  I believe that was the only difference between the two.  

Should the ML.Net Model Builder work inside a C# UWP app, or is it only designed to work with a console app?

I was also able to get the GPU to work, but found the installation instructions to be pretty frustrating and unclear.
![image](https://user-images.githubusercontent.com/20384698/187310266-56f3553d-51d2-4254-a4aa-7242645145fc.png)


Anyway, thanks for taking the time to respond to my post.  I am anticipating really enjoying using ML.Net Model Builder and am looking forward to learning more about it.  

Best regards.

**Comment by v-Hailishi** [comment] 2022-08-30 01:34
@beccamc I have tried on the latest main version 16.13.10.2242501, just like JohnMahanDavis said that the bug is reproducible when creating a C# UWP app.

**Comment by beccamc** [comment] 2022-09-19 20:03
@luisquintanilla We aren't expected to work with a UWP app are we?

**Comment by beccamc** [comment] 2022-09-19 20:04
@JohnMahanDavis Thanks for the feedback! Do you have suggestions for how the GPU instructions or information could be improved? What part was confusing and difficult to follow?

**Comment by luisquintanilla** [comment] 2022-09-19 20:56
> @luisquintanilla We aren't expected to work with a UWP app are we?

I'm not aware of any technical limitations that would keep MB from working on UWP apps. @JakeRadMSFT are you aware of anything?

**Comment by luisquintanilla** [comment] 2022-09-22 22:26
@JohnMahanDavis one thing I can think of to help unblock you here is:

1. Create a C# Class Library project and train your machine learning model there.
2. Reference the C# Class Library project containing the model in your UWP app.

**Comment by JohnMahanDavis** [comment] 2022-09-23 16:07
Luis and Team, Thanks for that suggestion.  It worked like a charm.  I was able to make the Model Builder work, but struggled some in the Consume Your Model section. Only two suggestions to improve clarity further for anyone else who might be in this predicament,:It would be helpful to mention at the beginning of the Consume Your Model step, to right-click on the Project Template that was added to the solution and select it as Set as Startup Project.  That might not be obvious to inexperienced learners.Copying and pasting the Program.cs code suggested in the tutorial did not work for me.  What did work was using the file that was auto-generated by ML.NET Model Builder.  I had to modify that code slightly to get the desired result, as shown in the attached screenshot below:I added a string variable, “InputClause”, to use in the call to the MLModelTest1.ModelInput() class.I commented out 3 lines of code as shown in the attachment followed by this comment //JMD commented out this line  That achieve the desired result and returned the proper prediction for a variety of tested input clauses as shown here:                Thanks again for helping me through this.  Would not have been successful without your advice.  Now I’m off to continue to learn and explore ML.Net Model Builder. Best regards, John Davis Sent from Mail for Windows From: Luis QuintanillaSent: Thursday, September 22, 2022 6:27 PMTo: dotnet/machinelearning-modelbuilderCc: JohnMahanDavis; MentionSubject: Re: [dotnet/machinelearning-modelbuilder] visual studio 2022 and ML.NET extension doesn't work (Issue ***@***.*** one thing I can think of to help unblock you here is:Create a C# Class Library project and train your machine learning model there.Reference the C# Class Library project containing the model in your UWP app.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by luisquintanilla** [comment] 2022-09-23 16:59
Hi @JohnMahanDavis 

Happy to hear you got it working. Thanks for that feedback. There are a few improvements we want to make to our generated code which we're tracking in #1638. I'll close this issue for now, but I'll create a new one to investigate using Model Builder with UWP. 

Thanks

**Closed by luisquintanilla** 2022-09-23 16:59 UTC

**Comment by JohnMahanDavis** [comment] 2022-10-11 08:49
The only confusing part was when I tried to add the Machine Learning module from a C# UWP solution, the Machine Learning Module failed to appear.  It only worked for me from inside of a C# Console App.So, the source of my confusion was due to the web page in the attached screenshot which indicates that it should work with UWP …  Thanks for your responses.John DavisSent from my iPhoneOn Sep 19, 2022, at 4:04 PM, Becca McHenry ***@***.***> wrote:﻿
@JohnMahanDavis Thanks for the feedback! Do you have suggestions for how the GPU instructions or information could be improved? What part was confusing and difficult to follow?
