### ISSUE TITLE
Update Package Fails

### ISSUE THREAD

**Issue by JakeRadMSFT** [dotnet/machinelearning-modelbuilder#2351] opened 2022-11-08 00:19 UTC
After getting prompted to upgrade my ML.NET Dependency to 2.0.0 ... I received this failure.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/31937616/200442837-59542683-bc0c-490f-82bd-4d78af21e65d.png">

**Comment by v-Hailishi** [comment] 2022-11-08 02:48
Verified on the latest main build 16.14.0.2255703 in VS2022, I also training failed with Model builder error.
![image](https://user-images.githubusercontent.com/99375895/200462946-966806d6-b71d-4650-b6a1-02b89d44e4cf.png)

**Comment by beccamc** [comment] 2022-11-08 17:10
@luisquintanilla Is this also blocking?

**Comment by beccamc** [comment] 2022-11-08 17:19
I assume this is happening when you have a project with an existing .mbconfig file (so it has a reference to an older ML.NET already) and then you re-run with the new 2.0 code.

**Comment by beccamc** [comment] 2022-11-08 19:09
I'm not getting a consistent repro of this. @JakeRadMSFT can you share any other details of the project? Anything stick out to you?

@luisquintanilla Is this a ship blocker if its not a consistent issue?

**Comment by beccamc** [comment] 2022-11-08 19:35
Yes there is a work around. People can manually update the Nuget package.

**Comment by luisquintanilla** [comment] 2022-11-08 19:36
Okay. Let's add it to the release notes.

**Comment by v-Hailishi** [comment] 2022-11-09 07:01
The bug had been fixed on the latest main build 16.14.0.2255803
![image](https://user-images.githubusercontent.com/99375895/200761099-deb45f87-c652-42d1-b392-d0295b741f17.png)
![image](https://user-images.githubusercontent.com/99375895/200761253-208af4bf-a5a1-4b66-8684-b31485300245.png)

**Comment by deiruch** [comment] 2022-11-12 17:12
> The bug had been fixed on the latest main build 16.14.0.2255803

I just ran into this issue with 16.14.0.2255902.

1. In a project where I used the previous ML Builder, create a new model
2. Click through the wizard, let it train for 10 minutes
3. At the end of the training, when creating the model, the wizard is trying to install NuGet packages. During that process, I was informed that I tried to install an old ML.NET version (1.7) and that there was a newer version (2.0) available. It asked me whether I wanted to upgrade to 2.0, which I agreed to. It installed Microsoft.ML and Microsoft.ML.LightGbm, and then it failed. Here's the last part of the log:

```
2022-11-12 18:05:51.7619 INFO Generate code behind files (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3883 INFO 

Copying generated code to project... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3972 INFO Copying MLModel1.consumption.cs to folder: C:\Users\de\OneDrive - iru.ch\Source\WarengruppenKlassifizieren\WarengruppenKlassifizieren (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3972 INFO Copying MLModel1.training.cs to folder: C:\Users\de\OneDrive - iru.ch\Source\WarengruppenKlassifizieren\WarengruppenKlassifizieren (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3972 INFO COMPLETED (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3972 INFO 

Updating nuget dependencies... (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.3972 INFO Starting update NuGet dependencies async. (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:05:54.4166 INFO Installing nuget package, package ID: Microsoft.ML, package Version: 2.0.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:07:07.8805 INFO Microsoft.ML has been updated successfully (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:07:07.8805 INFO Installing nuget package, package ID: Microsoft.ML.LightGbm, package Version: 2.0.0 (Microsoft.ML.ModelBuilder.Utils.Logger.Info)
2022-11-12 18:07:10.2990 DEBUG Package restore failed. Rolling back package changes for 'WarengruppenKlassifizieren'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalCoreAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.ML.ModelBuilder.Utils.Utilities.<InstallNugetPackageAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<UpdateNugetDependenciesAsync>d__106.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.ML.ModelBuilder.ViewModels.TrainViewModel.<GenerateCodeBehindFilesAsync>d__105.MoveNext() (Microsoft.ML.ModelBuilder.Utils.Logger.Debug)
```

**Comment by JakeRadMSFT** [comment] 2022-11-14 21:22
Thanks @deiruch -  I didn't have a consistent repo but it does seem like this happens fairly consistently with old projects to new projects.

We'll investigate!

**Comment by luisquintanilla** [comment] 2022-11-14 21:52
Additional behaviors to look into:

- Not all packages (only Microsoft.ML) are updated

Investigate into how update process (especially for major versions) can be more robust.

**Comment by luisquintanilla** [comment] 2022-11-14 21:55
@deiruch did manually upgrading versions fix your issue?

**Comment by deiruch** [comment] 2022-11-15 09:45
> @deiruch did manually upgrading versions fix your issue?

Yes, since I upgraded, it works as expected.

**Comment by luisquintanilla** [comment] 2022-11-16 21:50
@JakeRadMSFT to add more details.

**Comment by zewditu** [comment] 2022-11-18 00:48
It seems that it happens only for  LightGbm , other packages upgraded themselves automatically  ,
@LittleLittleCloud   what makes LightGbm special for does not upgrade automatically ?

**Comment by luisquintanilla** [comment] 2022-12-13 22:19
@zewditu I think I heard you mention you ran into this during bug bash. 

I was unable to repro when training a data classification model using LightGBM.

![Image](https://user-images.githubusercontent.com/46974588/207456890-2b3561bf-9019-4644-84e7-80881917f660.png)

**Comment by zewditu** [comment] 2022-12-14 18:05
> @zewditu I think I heard you mention you ran into this during bug bash.
> 
> I was unable to repro when training a data classification model using LightGBM.
> 
> ![Image](https://user-images.githubusercontent.com/46974588/207456890-2b3561bf-9019-4644-84e7-80881917f660.png)
 
Thanks for confirmation!  As jack said the bush build may not include some PRS, I also not able to reproduce it from the latest main.

Either way it is fixed.

**Closed** 2022-12-14 19:15 UTC
Labels: Priority:0
