### ISSUE TITLE
Create experiment dialog does not display already existed subscriptions 

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#563] opened 2020-03-04 21:19 UTC
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**

**Steps to Reproduce**
1. Select Image classification  from scenario page
2. Select Azure  training
3. Click cancel button on create new experiment dialog
4.Again select Azure training 
5. Click on subscription drop down in create new experiment dialo

**Expected Experience**
List of already existed subscriptions should be populated 

**Actual Experience**
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/1184d8e5-ab63-4c43-8420-ab41d6876d09)_
**Additional Context**
 The bug is in our  latest branch not in our  February release

**Comment by JakeRadMSFT** [comment] 2020-03-09 21:35
@zewditu can you sync with Becca? Is this something with the new environment tab ... or is this a regression in Master?

**Comment by beccamc** [comment] 2020-03-09 22:04
I think this is a dup of https://github.com/dotnet/machinelearning-modelbuilder/issues/539.  Its happening on the reload of the dialog right? Good find!

**Comment by zewditu** [comment] 2020-03-10 01:45
@JakeRadMSFT  , @beccamc  is right I am sure that it  is not because of environment tab.

**Comment by JakeRadMSFT** [comment] 2020-03-10 19:57
Closing as duplicate of #539

**Closed by JakeRadMSFT** 2020-03-10 19:57 UTC
