### ISSUE TITLE
Add Machine Learning at VS2019 solution does nothing

### ISSUE THREAD

**Issue by raphael-dossantos** [dotnet/machinelearning-modelbuilder#1542] opened 2021-06-29 13:50 UTC
**System Information (please complete the following information):**
 - Model Builder or CLI Version:  
 - Visual Studio Version 2019 Enterprise: 16.8.2

**Describe the bug**
- On which page of the tutorial did you run into an issue (URL):
- Clear description of the problem:

**To Reproduce**
1. Go to Solution Explorer
2. Right click on console application
3. Scroll down to Add > Machine Learning
4. Nothing happens

**Expected behavior**
ML.NET Builder screen shows up

**Comment by torronen** [comment] 2021-06-30 13:43
@raphael-dossantos  Did you enable the Preview feature from Tools | Options page? If not, there should be a very small notice in Visual Studio asking to do it, but it is easy to miss. 

![image](https://user-images.githubusercontent.com/26261427/123970635-f5c25000-d9c1-11eb-861f-d914c67fafba.png)

![image](https://user-images.githubusercontent.com/26261427/123970546-de836280-d9c1-11eb-8201-27e4fb3b10ac.png)

Console Application probably needs to use .NET Core or .NET 5.0 framework (according to issue https://github.com/dotnet/machinelearning-modelbuilder/issues/1511 )

**Comment by beccamc** [comment] 2021-07-01 15:06
@raphael-dossantos In addition to Antti's suggestions, are you trying to add to VB project? We only support C#.

**Comment by raphael-dossantos** [comment] 2021-07-01 17:23
Thanks for repplies, I really appreciate. I'm using C# not VB and I did enabled Preview Tools. Let me try .NET 5, because I was using 3.1.

I'll try and let you know.

Thanks for all kind repplies.

**Comment by torronen** [comment] 2021-07-03 14:37
I once had disabled the extension by accident. Probably from the notice telling it caused X seconds of unresponsiveness. I think it did the same as you describe. That could be one cause also.

**Comment by beccamc** [comment] 2021-07-15 16:07
Any update here @raphael-dossantos?

**Comment by torronen** [comment] 2021-07-16 12:19
I have same issue with Visual Studio 2022, just now trying. Same project works on VS 2019. I'll still try on another machine. 

After right-clicking on project, Add > Machine Learning it asks me to select file type without Machine Learning.

![image](https://user-images.githubusercontent.com/26261427/125946247-a8408852-739b-4925-a392-0bf281a71f5e.png)

**Comment by beccamc** [comment] 2021-07-21 20:01
@torronen Thanks for your help diagnosing this issue. I've added this problem to our troubleshooting document [here](https://github.com/dotnet/machinelearning-modelbuilder/blob/main/troubleshooting/ModelBuilderTroubleshooting.md#i-cannot-add-machine-learning-to-my-project).  If you want to take a look you can let me know if you have suggestions/improvements. 

We're working to get VS 2022 available now. The VS Marketplace blocks installing into VS 2022. It seems like the version available in 2022 is the older build that ships with VS? @LittleLittleCloud FYI, looks like the menu option is available in 2022.

**Comment by torronen** [comment] 2021-07-21 21:13
Oh, I see. So the VS 2022 is unrelated to problem reported by @raphael-dossantos 

Not sure if you mean this, but my installation got a pretty recent version (16.6.2.2132901 dated 17/16/2021) of ML.NET Model Builder installed in VS 2022 Enterprise just installed a few days ago. Trying to uninstall it takes to VS installer so it is probably the one that ships with the installer
![image](https://user-images.githubusercontent.com/26261427/126560729-1713e9f8-95f9-4807-9033-0bcb557e4871.png)

**Comment by acrigney** [comment] 2021-07-28 04:57
I have the same problem with the latest VS2022 v 2.1 on a fresh new windows server.

**Comment by LittleLittleCloud** [comment] 2021-08-02 22:57
@torronen @raphael-dossantos 
While we are looking into this issue, (it looks quite similiar with #1511). Since ModelBuilder wizard will be used for file with extension as `.mbconfig` so if "Add machine learning" doesn't work, a work-around is creating a file with `.mbconfig` as extension directly.

@acrigney
which model builder version do you have on VS2022

**Comment by acrigney** [comment] 2021-08-03 00:31
My model builder version on VS2022 is
16.6.1.2131904
and its set to auto update.
And the project type is .net 6

And what does he mean when he says "create a file with the .mbconfig
extension? Where and please explain more?

**Comment by vzhuqin** [comment] 2021-08-03 07:24
I have the same issue on: 
- ML.Net Model Builder (Preview): 16.7.2.2140201 (Main Branch)
- Microsoft Visual Studio Enterprise 2022 Preview: 17.0.0 Preview 2.1
- .Net: 5.0.302

Found that can add model builder by the following steps, @LittleLittleCloud please take a look, if this is the expected behavior?
1. Right click to select Add> Machine Learning;
2. Navigate to "Visual C# Items" on the "Add New Item - xxx" dialog;
3. Select Machine Learning Model (ML.NET);
4. Click "Add" button.
![Add model builder on VS2022](https://user-images.githubusercontent.com/81727020/127973678-0aa79dbc-a88f-407b-a3c5-a079eb12a874.gif)

**Comment by LittleLittleCloud** [comment] 2021-08-03 17:34
I tried the VS2022 preview3 and it seems this issue no longer exists. Maybe it's a bug from VS add to item window and has been fixed already/ In that case,  I suggest we don't fix this bug as it's not a blocking issue and will be fixed once the next VS2022 preview comes out.

![image](https://user-images.githubusercontent.com/16876986/128059821-97b8b15a-5e37-49cf-a64f-482db977dbc3.png)
![image](https://user-images.githubusercontent.com/16876986/128059914-f60d13da-ea1e-4e64-8761-ee8a57ec120d.png)

**Closed** 2021-08-09 19:05 UTC
Labels: Customer Reported, GS Tutorial
