### ISSUE TITLE
"Training cancelled" error occurs during model training

### ISSUE THREAD

**Issue by vkurlov** [dotnet/machinelearning-modelbuilder#449] opened 2020-01-17 05:21 UTC
**System Information:**
 - Model Builder Version: 16.0.1911.1103
 - Visual Studio Version: VS 2019 (16.4.2)

**Describe the bug**
"Training cancelled" error occurs during model training.
The model training fails accidentally (my guess), sometimes after 100 iterations, sometimes after 3000 iterations

**Screenshots**

![2](https://user-images.githubusercontent.com/36929620/72586201-2a039700-391b-11ea-8ba9-619ff863684c.png)

![1](https://user-images.githubusercontent.com/36929620/72586200-2a039700-391b-11ea-9247-26e204bdd311.png)

What is wrong, any help please...

**Comment by LittleLittleCloud** [comment] 2020-01-17 21:14
Thanks for your feedback! We will look into that

Seems to be known issue @JakeRadMSFT 
#284 


In the meanwhile, it seems the trainer's status is not quite stabilized (see R-square), Is that a known issue in AutoML? @justinormont

**Comment by justinormont** [comment] 2020-01-17 22:34
**Bug for** `Training cancelled` **:**
I think @LittleLittleCloud is correct in saying we've seen the error before. @vkurlov is there a stacktrace in the log file? Adding more info to https://github.com/dotnet/machinelearning-modelbuilder/issues/284 may be helpful. 

**Stability:**
The R-squared values in the screenshot looks normal to me. A negative R-squared implies the model is worse than a trivial model (one that always predict the average of the label value). Negative R-squared can _also_ be caused by data drift if your validation dataset is from a different distribution than your training dataset, but since Model Builder only accepts a single dataset this generally can't occur besides for very small datasets.  Normally you should expect the R-squared metric to be between [0..1] for any useful model. 

Expect stabilization starting around iteration ~72, and generally leveling off around ~150. Between iteration ~12 to ~72, the AutoML is doing random sweeping for the warm-up phase of SMAC. Plus ~11 iterations to try a baseline run on all trainers. Once SMAC begins, around iteration ~72, the values will spend more time near the optimal scores. You can graph the score vs. iteration, and you'll see the transition point.

**Comment by vkurlov** [comment] 2020-01-20 04:30
I attached logs:
[logs.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4084428/logs.zip)

**Comment by LittleLittleCloud** [comment] 2020-03-23 18:16
dup of #284

**Comment by LittleLittleCloud** [comment] 2020-04-21 19:37
Close this since it's a dup of #284

**Closed** 2020-04-21 19:37 UTC
Labels: Customer Reported
