### ISSUE TITLE
When data downloaded from sql server, the user is not able to cancel the data-download( button is inactive )and the button doesn't show appropriate label  like  "Cancel download "

### ISSUE THREAD

**Issue by zewditu** [dotnet/machinelearning-modelbuilder#198] opened 2019-07-29 22:29 UTC
**Model Builder Version**: _In which Model Builder version was the bug encountered?_
**Visual Studion Version**: _In which Visual Studio version was the bug encountered?_

**Bug description**
_A clear and concise description of what the bug is._

**Steps to Reproduce**
1. _List the minimal steps required to reproduce the bug._
2. _Thanks for reporting!_

**Expected Experience**
_A description of what you expected to happen. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what you expected._

**Actual Experience**
_A description of what actually happens. If applicable, add screenshots or "Machine Learning" Output Logs to help explain what actually happened._

**Additional Context**
_Add any other context about the problem here, such as unusual system configurations, network restrictions, etc._
![Capture.PNG](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/9d403a2f-1302-4587-a908-9b16587d4ec1)

**Comment by JakeRadMSFT** [comment] 2020-03-02 02:35
Duplicate of 103

**Closed by JakeRadMSFT** 2020-03-02 02:35 UTC
Labels: M (T-shirt size - Max 5 days), P2
