### ISSUE TITLE
Error "ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions" when training Model in Azure

### ISSUE THREAD

**Issue by marxxxx** [dotnet/machinelearning-modelbuilder#2978] opened 2024-10-07 16:55 UTC
**System Information (please complete the following information):**
 - Model Builder Version 17.18.4.2425601: 
 - Visual Studio Version 17.11.4

**Describe the bug**
Starting today i get an exception when i train an image classification model on Azure.
I follow the usual Model Builder Wizard, 
Error initializing model :Microsoft.ML.OnnxRuntime.OnnxRuntimeException: [ErrorCode:Fail] Load model from `D:\Dev\SWA\Solution\Project\xxx\xxx.onnx failed:D:\a\_work\1\s\onnxruntime\core/graph/model_load_utils.h:57 onnxruntime::model_load_utils::ValidateOpsetForDomain ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 17 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 15.`

   at Microsoft.ML.OnnxRuntime.NativeApiStatus.VerifySuccess(IntPtr nativeStatus)
   at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at Microsoft.ML.OnnxRuntime.InferenceSession..ctor(String modelPath, SessionOptions options)
   at Microsoft.ML.Transforms.Onnx.OnnxModel..ctor(String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, Boolean ownModelFile, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)

   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, Options options, Byte[] modelBytes)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer..ctor(IHostEnvironment env, String[] outputColumnNames, String[] inputColumnNames, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit, Nullable`1 interOpNumThreads, Nullable`1 intraOpNumThreads)
   at Microsoft.ML.Transforms.Onnx.OnnxScoringEstimator..ctor(IHostEnvironment env, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu, IDictionary`2 shapeDictionary, Int32 recursionLimit)
   at Microsoft.ML.OnnxCatalog.ApplyOnnxModel(TransformsCatalog catalog, String modelFile, Nullable`1 gpuDeviceId, Boolean fallbackToCpu)
   at AzureML.AutoMLRunnerImages.GetBestModelAndPipelineImageClassification(MLContext mlContext, String modelFile) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 276
   at AzureML.AutoMLRunnerImages.RunAutoMLAsync(MLContext mLContext, CancellationToken cancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/RemoteAutoML/AutoMLRunnerImages.cs:line 202
   at Microsoft.ML.ModelBuilder.AutoMLService.Experiments.AzureImageClassificationExperiment.ExecuteAsync(IDataView trainData, IDataView validateData, CancellationToken ct) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/Experiments/AzureImageClassificationExperiment.cs:line 60
   at Microsoft.ML.ModelBuilder.AutoMLEngine.StartTrainingAsync(ITrainingConfiguration config, PathConfiguration pathConfig, CancellationToken userCancellationToken) in /_/src/Microsoft.ML.ModelBuilder.AutoMLService/AutoMLEngineService/AutoMLEngine.cs:line 178

**To Reproduce**
- select a local directory with classified images
- hit "train" button
- let training finish (Job in Azure Machine Learning Studio finishes successful as well)
- Model Builder downloads the model, generates the onnx Model but then shows a popup with the error. 
- The mlnet model is not generated.

**Expected behavior**
- I get a mlnet model and the process completes without error.

**Additional context**
Azure Machine Learning Run Id:  https://ml.azure.com/experiments/id/4635c1c0-3935-446b-a646-0036551de5cf/runs/zeihheakczitmky?wsid=/subscriptions/c7c553dd-b8f1-451b-96c6-b5111f449abb/resourceGroups/wireterminal-ml-dev/providers/Microsoft.MachineLearningServices/workspaces/wireterminal-ml-studio-dev

**Comment by LittleLittleCloud** [comment] 2024-10-18 05:06
Looks like a warning that we can disable as a temporary workaround? The root cause might be azure ml service upgrade their onnx version? Need further investigation.


@michaelgsharp Is there an option disable that check on mlnet onnxruntime transformer side?

**Comment by v-Hailishi** [comment] 2024-10-25 04:39
@LittleLittleCloud Verified on the latest main build 17.18.4.2445902, The azure training also failed.
![Image](https://github.com/user-attachments/assets/02b0d8c2-d342-4764-b12f-61287990bb79)

Run id:  
https://ml.azure.com/experiments/id/f411c83b-fdf5-4e70-9bee-1c54faed9462/runs/oaqhdxuryalqery?wsid=/subscriptions/95a6233a-023b-4ba2-b994-50066ea80ba1/resourceGroups/LocTest/providers/Microsoft.MachineLearningServices/workspaces/FullTestPass&tid=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by v-Hailishi** [comment] 2024-11-07 06:26
@LittleLittleCloud The azure training is successful on the latest main build 17.19.02455701.
![Image](https://github.com/user-attachments/assets/1fdc293b-952c-41d2-b2ce-80553814d824)
![Image](https://github.com/user-attachments/assets/25b66976-0aca-48a0-bf5f-443943158f59)
![Image](https://github.com/user-attachments/assets/2a852d20-f660-4a07-8a62-a9495ab6bbc4)

**Comment by v-Hailishi** [comment] 2024-11-07 06:48
@LittleLittleCloud The generated Console app and Web API projects are running failed for "Image Classification" scenario.
![Image](https://github.com/user-attachments/assets/c0a56050-0c12-4848-980b-5682032f2954)
![Image](https://github.com/user-attachments/assets/6fecf90a-1f13-4912-8a3c-b6a3052b1fe3)

**Comment by v-Hailishi** [comment] 2024-11-08 02:19
@LittleLittleCloud After updating generated project's onnxruntime dependency to 1.20.0 manually, the running can be successful.
![Image](https://github.com/user-attachments/assets/91ac6445-06b0-4e71-80eb-22e33fd864e7)
![Image](https://github.com/user-attachments/assets/b2cdfbae-2f13-4db5-9633-a9065bff48f8)
![Image](https://github.com/user-attachments/assets/ec2dd863-5f68-4a1a-be17-a8eba0efd9bd)

**Comment by v-Hailishi** [comment] 2024-11-15 09:02
The bug has been fixed on the latest main build 17.19.0.2456401 for "Image Classification-Azure" scenario, the auto installed onnxruntime package version is 1.20.0.
![Image](https://github.com/user-attachments/assets/6c2c07c1-4a61-4cfc-863e-74fde5d0e48b)

**Comment by inxyte** [comment] 2024-11-28 17:25
Hello,

I am getting the same issue after no issues for some time.  I've uninstalled/reinstalled VS2022 and also attempted using upgraded 17.13 Preview 1 of VS2022.  For some reason I am unable to upgrade to the latest Model Builder Extensions from 17.18 to 17.19 as VS2022 reports it's already installed but the Extensions Manager shows it as still available to upgrade.    Since it's at least downloading an ONNX model, I can at least publish the newly trained ONNX model to my production application - but I had to slightly changed the generated pipeline away from the MLNet produced version of the model...

I think AzureML upgraded the packages in their training latest training environment Docker Container causing the ONNX OpSet mis-match...  

Thanks in Advance...

**Comment by LittleLittleCloud** [comment] 2024-11-28 18:50
@inxyte There's something wrong in the latest update `17.19.0` to vs marketplace, we are working on making another release, which will be available after thanksgiving.

I also uploaded the right`17.19.0` to google drive if you don't want to wait for another release
- https://drive.google.com/file/d/1DNnHBpEwK_7Rcvt8GKpCjJXXLRWvWczo/view?usp=drive_link

**Comment by LittleLittleCloud** [comment] 2024-12-03 16:25
FIxed in 17.19.1

**Closed as completed by LittleLittleCloud** 2024-12-03 16:25 UTC

**Comment by inxyte** [comment] 2024-12-04 07:54
Hello,

Thanks for this turnaround...  I was able to upgrade to this latest version of the Builder in VS2022 17.13 Preview 1 with no issue.  I'm running a new Azure Hosted Image Classification training run now.  I'll post here again if issue with the final results, but so far, so good...

Thanks again!
eem

**Comment by inxyte** [comment] 2024-12-04 08:36
> Hello,
> 
> Thanks for this turnaround... I was able to upgrade to this latest version of the Builder in VS2022 17.13 Preview 1 with no issue. I'm running a new Azure Hosted Image Classification training run now. I'll post here again if issue with the final results, but so far, so good...
> 
> Thanks again! eem

Azure ML Submitted Image Classification Job finished and downloaded and then converted from ONNX to mlnet no issues. So much appreciated!  

Cheers,
eem
