### ISSUE TITLE
Status: Failed. See more in Output Pane. But there is no information or exception in the output pane

### ISSUE THREAD

**Issue by kartikdash1** [dotnet/machinelearning-modelbuilder#408] opened 2019-12-18 06:00 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by JakeRadMSFT** [comment] 2019-12-20 21:07
Duplicate of #402

**Closed** 2019-12-20 21:07 UTC
