### ISSUE TITLE
Suggestion: Allow users to choose model selection criteria & show full results of test

### ISSUE THREAD

**Issue by torronen** [dotnet/machinelearning-modelbuilder#1537] opened 2021-06-28 17:28 UTC
At the moment Model Builder uses internal method of selecting the model it thinks it is best. However, this depends on the contexts and users should be able to select the criteria. Wrong selection criteria may lead to selection of the wrong (for that case) model.

![image](https://user-images.githubusercontent.com/26261427/123677910-56308080-d84e-11eb-94d4-47455d5dec5d.png)
![image](https://user-images.githubusercontent.com/26261427/123677923-59c40780-d84e-11eb-9c8d-0e67f791e7a9.png)
_Imbalanced binary text classification selected macro accuracy of 0.5 in favor of micro accuracy_

**Describe the solution you'd like**
Allow to select if micro or macro or other available criteria should be used to select the "best" model.

If possible, I'd like to also see the raw numbers of true positives, false positives, true negatives and false negatives.

**Comment by LittleLittleCloud** [comment] 2021-06-29 18:53
@briacht another call-out for customizing model selection criteria.

The metrics that are available for selection can be
| scenario | metric |
| - | - |
| multi-class classification| macro accuracy, micro accuracy, log loss |
| binary-class classification | accuracy, auc |
| regression | r-square, rmse |

@torronen @justinormont feel free to ask for more metrics

And @torronen , looks like your dataset is binary? Small tip, You can run binary classification by setting the label type to boolean in advanced dataset option if your label can be converted to boolean. ( in format of 0/1, true/false, T/F..).

**Comment by torronen** [comment] 2021-07-20 21:19
Should model size taken into account? If two models are performing identically (or near), perhaps, smaller model should be chosen for performance and to avoid risk of overfitting. It might be difficult to make a balanced decision between size vs. performance.

**Comment by briacht** [comment] 2021-07-22 19:33
Related to #207

**Comment by beccamc** [comment] 2022-04-25 18:52
Removing from DRI issue. This should be rolled into Advanced Training Options.

**Comment by luisquintanilla** [comment] 2022-09-22 20:00
Closing this issue since it's already being tracked and worked on in Advanced Training Options #2191 as well as #1582  

Thanks @torronen

**Closed by luisquintanilla** 2022-09-22 20:00 UTC
Labels: Reported by: Customer, Priority:1, Code Example?
