### ISSUE TITLE
CLI should generate code that fits the culture of the OS Language 

### ISSUE THREAD

**Issue by vardeg2017** [dotnet/machinelearning-modelbuilder#93] opened 2019-06-05 09:06 UTC
Model Builder 16.0.1905.641
OS Windows 10 Pro 17134.765
VS Studion 2019 16.1.1

OS Windows has Default Lungauge setted to Russian. It the same like CultureInfo by default is "ru-RU". So presentation of my float and double is 0,001 instead of 0.001
For this reason in code i use CultureInfo to parse and write data written in "en-EN" format with dot separated style and "ru-RU" with comma separated style when i need it.

I'm not shure but i think that this error is depends on my System Language set.
ModelBuilder generate code and write in one method float number using default "ru-RU" localisation and used comma instead of dot. So i got error in code.

ConsoleApp namespace => ModelBuilder class => BuildTrainingPipeline method:
var trainer = mlContext.BinaryClassification.Trainers.SdcaLogisticRegression(new SdcaLogisticRegressionBinaryTrainer.Options() { L2Regularization = **0, 0001f**, L1Regularization = 0f, ConvergenceTolerance = **0, 001f**, Shuffle = true, BiasLearningRate = 1f, LabelColumnName = "Label", FeatureColumnName = "Features" });

and mast be:
var trainer = mlContext.BinaryClassification.Trainers.SdcaLogisticRegression(new SdcaLogisticRegressionBinaryTrainer.Options() { L2Regularization = **0.0001f**, L1Regularization = 0f, ConvergenceTolerance = **0.001f**, Shuffle = true, BiasLearningRate = 1f, LabelColumnName = "Label", FeatureColumnName = "Features" });

**Comment by rustd** [comment] 2019-06-06 15:53
@JakeRadMSFT can you please look into this or re-assign?

**Comment by twsI** [comment] 2019-06-07 08:51
Can confirm this with german. I guess, someone is missing `.ToString(CultureInfo.InvariantCulture);` or something similar

**Comment by rustd** [comment] 2019-06-10 18:24
Can you please resolve this as a duplicate of the master issue on AutoML or CLI?

**Comment by rustd** [comment] 2019-07-08 22:13
Please verify with the 0.14 CLI version that we will ship with.

**Comment by LittleLittleCloud** [comment] 2019-07-09 19:19
@vardeg2017 Can I have your dataset, it will be great help to me

**Comment by JakeRadMSFT** [comment] 2019-07-31 21:22
Test that this is resolved with latest CLI/ML.NET

**Comment by LittleLittleCloud** [comment] 2019-08-09 18:16
resolved

**Closed** 2019-08-15 21:52 UTC
Labels: Customer Reported, Localization, M (T-shirt size - Max 5 days), P1
