### ISSUE TITLE
Can't go to Consume. The "Next Step" button is gray.

### ISSUE THREAD

**Issue by xfpinyu** [dotnet/machinelearning-modelbuilder#1186] opened 2021-01-22 02:12 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
- On which step of the process did you run into an issue:
- Clear description of the problem:

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xfpinyu** [comment] 2021-01-22 02:14
![image](https://user-images.githubusercontent.com/42860835/105436681-989bd300-5c9a-11eb-85c8-5f0b293d192e.png)

**Comment by beccamc** [comment] 2021-01-23 00:08
@xfpinyu Sorry you ran into this issue! It looks like you're doing text classification? The menu on the left is also disabled, correct?

**Comment by xfpinyu** [comment] 2021-01-24 05:48
correct



---Original---

**Comment by beccamc** [comment] 2021-02-12 22:24
@xfpinyu Sorry for my long delay here. Does the problem reproduce, or did it only happen once?

**Comment by beccamc** [comment] 2021-03-17 00:14
@xfpinyu Is this still happening for you?

**Comment by beccamc** [comment] 2021-03-22 16:25
Closing this. Please re-open and @ mention me if it is still an issue. Thanks!

**Closed by beccamc** 2021-03-22 16:25 UTC
