### ISSUE TITLE
Referenced sample does not have file header

### ISSUE THREAD

**Issue by natke** [dotnet/machinelearning-modelbuilder#70] opened 2019-05-31 22:06 UTC
This example data set does not have a header, and Model Builder requires data files to have a header: https://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip

Without extra information, this would cause confusion if a user tried Model Builder with this dataset.

Reference from this file: https://github.com/dotnet/machinelearning-samples/tree/master/modelbuilder

**Comment by rustd** [comment] 2019-06-03 19:37
Duplicate of  #74

**Closed by rustd** 2019-06-03 19:37 UTC
