### ISSUE TITLE
Comma decimal separator causes failure on evaluate

### ISSUE THREAD

**Issue by AndersH92** [dotnet/machinelearning-modelbuilder#402] opened 2019-12-15 16:35 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When I press "Start training" in the model builder I get the status "Failed. See more in the Output Pane". The problem is that no message appear in the Output pane, or am I missunderstanding what the output pane is? (see attached image)

![Skärmklipp](https://user-images.githubusercontent.com/22051631/70865725-f1118480-1f60-11ea-8bc3-d5aa087b332e.PNG)

Windows version: Windows 10 Enterprise version 1803
OS version: 17134.1130

Regards
Anders H

**Comment by JakeRadMSFT** [comment] 2019-12-20 21:06
Do you happen to have a 32bit version of Windows?

**Comment by quocdai92** [comment] 2020-01-31 07:09
Still happen :|

**Comment by beccamc** [comment] 2020-04-14 17:37
@AndersH92 Is this issue still happening? Could you share the dataset you were working with?

@quocdai92 Can you provide more details? Could you also provide the dataset you are working with? 

Is the dataset failing because it runs out of time? You should see an error message pop up if that happens.

**Comment by AndersH92** [comment] 2020-04-15 17:11
@beccamc No, I get one step further in the process. I.e. I get to evaluate step. However, there I get an error that say's that the input value is in the wrong format.

**Comment by beccamc** [comment] 2020-04-15 20:07
@AndersH92 Can I see a screenshot of the error message and the data you're using?

**Comment by beccamc** [comment] 2020-04-21 20:28
@AndersH92 Friendly ping! Could I get a screenshot of the input value problem? Does correcting the input value fix it?

**Comment by AndersH92** [comment] 2020-04-22 15:53
@beccamc Please see the screenshot below. I don't really know what's wrong with the input format, hence I don't know how to fix it. I also attach a copy of the data that I'm using. Column 10 is the value to predict and the others arre features.


![image](https://user-images.githubusercontent.com/22051631/80003783-cb255f00-84c1-11ea-8b12-48e1673728bd.png)

[test_ML_data.zip](https://github.com/dotnet/machinelearning-modelbuilder/files/4517266/test_ML_data.zip)

**Comment by beccamc** [comment] 2020-05-07 22:25
@AndersH92 Sorry for the delay in getting back to you. I'm trying to reproduce the problem you're experiencing. It looks like you're machine is in a different language? I've changed mine to also have "," for the decimal separator. 

![image](https://user-images.githubusercontent.com/9122518/81350339-8deece80-9076-11ea-81db-0486b2000d02.png)

I've tried both , and . as the decimal in the Evaluate data. I see no error. My VS is displaying numbers with "," separator. Is your VS in another language? I changed my Windows language but not my VS language. 

If you try to use 1221,79 as the first value is there still an error?

**Comment by AndersH92** [comment] 2020-05-09 11:29
No worries @beccamc. Yes it's in Swedish. I changed from "." to "," for the decimal separator in the sample data for prediction (i.e. 1221.79 -> 1221,79 for example) and it worked. Thanks! I find it strange though because it has obviously trained with the "." convention but is not able to evaluate on the same format?

**Comment by beccamc** [comment] 2020-06-22 20:16
@AndersH92 I was able to successfully evaluate your dataset on our latest build (16.1.0.2027905). If you want you could download our latest build and see if you can use the `.` on the Evaluate Try It Out experience.

**Comment by beccamc** [comment] 2020-07-08 20:15
Based on my testing this is fixed in version 16.1.0.2027905. If any comma separator users run into this again please ping we and we can reopen!

**Closed by beccamc** 2020-07-08 20:15 UTC
Labels: Customer Reported
