### ISSUE TITLE
ML.NET version not compatible with version 3.0+

### ISSUE THREAD

**Issue by abhaydubey** [dotnet/machinelearning-modelbuilder#358] opened 2019-11-20 20:01 UTC
Problem encountered on https://dotnet.microsoft.com/learn/ml-dotnet/get-started-tutorial/train
Operating System: macos Catalina

 MyMLApp % dotnet tool uninstall mlnet -g
Tool 'mlnet' (version '0.15.1') was successfully uninstalled.
 MyMLApp % dotnet tool install -g mlnet
Tools directory '/Users/USER/.dotnet/tools' is not currently on the PATH environment variable.
If you are using zsh, you can add it to your profile by running the following command:

cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/USER/.dotnet/tools"
EOF

And run `zsh -l` to make it available for current session.

You can only add it to the current session by running the following command:

export PATH="$PATH:/Users/USER/.dotnet/tools"

You can invoke the tool using the following command: mlnet
Tool 'mlnet' (version '0.15.1') was successfully installed.
 MyMLApp % mlnet
zsh: command not found: mlnet
 MyMLApp % cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/USER/.dotnet/tools"
EOF
 MyMLApp % echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools
 MyMLApp % zsh -l
 MyMLApp % mlnet
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
 MyMLApp %

**Comment by JakeRadMSFT** [comment] 2019-11-21 07:44
Thanks for reporting! We're looking into migrating to 3.0 for the next release.

**Comment by JakeRadMSFT** [comment] 2020-01-13 07:25
Duplicate of #256

**Closed** 2020-01-13 07:25 UTC
Labels: P0
