### ISSUE TITLE
Confusing Labels

### ISSUE THREAD

**Issue by ddobric** [dotnet/machinelearning-modelbuilder#457] opened 2020-01-24 08:36 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 
  <PackageReference Include="Microsoft.ML" Version="1.4.0" />
    <PackageReference Include="Microsoft.ML.ImageAnalytics" Version="1.4.0" />
    <PackageReference Include="Microsoft.ML.Vision" Version="1.4.0" />
	<PackageReference Include="SciSharp.TensorFlow.Redist" Version="1.14.0" />

 - Visual Studio Version
16.3.10

**Confusing Results**
I have provided a list of images as shown at the picture below:
![image](https://user-images.githubusercontent.com/1756871/73055037-25476180-3e8c-11ea-8f8c-3a97fa7d0027.png)

Assuming I have understand correctly the labeling in the builder, my expectation is to have labels like 51277179,..

After training, evaluation etc. I get following result for label:  5,127718E+07 and predicted value:  9,594217E+07.

![image](https://user-images.githubusercontent.com/1756871/73055161-70fa0b00-3e8c-11ea-9ff0-b9d540415a9e.png)

My expectation is to get result like label=51277179, predicted value=95.94217%.

Am I doing something wrong or is my expectation wrong?

**Comment by beccamc** [comment] 2020-01-29 01:58
Thanks for reporting @ddobric!  It definitely looks like something wrong on our end. It seems we're reading your labels in as numbers instead of strings, and then because they're so large we convert them into scientific notation. I assume you're machine is in European location, and that's why its using a comma for the decimal separator?

Your results are actually showing two labels. The actual label of the image is 51277179, but the model predicted 9594217x (your final digit looks cutoff due to the wacky string -> number -> scientific notation). 

Let me try to reproduce this so we can get a fix in.

**Comment by LittleLittleCloud** [comment] 2020-03-23 18:25
This should be fixed after we stop parsing multi-classification's label as bool or single

**Comment by LittleLittleCloud** [comment] 2020-03-23 18:46
Stop parsing label as types other than string in classification should fix this.

**Comment by zewditu** [comment] 2020-04-06 22:36
validated 
![image.png](https://images.zenhubusercontent.com/5d014b8c2b5aa11c6166d13d/362f8b70-4ab0-4ca0-b038-b9506aaae878)

**Closed** 2020-05-14 18:59 UTC
Labels: Customer Reported
