### ISSUE TITLE
Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies

### ISSUE THREAD

**Issue by mktamal** [dotnet/machinelearning-modelbuilder#204] opened 2019-08-04 13:50 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/data
Operating System: windows 10

I am encountering this issue while uploading .tsv file for building machine learning model. I am using VS 2017 Version 15.9.14 and framework version 4.6.01055

**Comment by rustd** [comment] 2019-08-07 20:53
@mktamal can you please fill out the following information which will help us debug this issue.

**System Information (please complete the following information):**
 - Model Builder Version: 
 - Visual Studio Version

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by JakeRadMSFT** [comment] 2019-09-20 21:22
Resolving issue because we haven't received a response. If you're still having this issue, please re-open and include the requested details.

Cheers,
Jake

**Closed by JakeRadMSFT** 2019-09-20 21:22 UTC
Labels: Customer Reported
