### ISSUE TITLE
'Invalid initializer member declarator' in Generated ModelBuilder.cs when OS Culture is Finnish

### ISSUE THREAD

**Issue by tparviainen** [dotnet/machinelearning-modelbuilder#58] opened 2019-05-23 17:12 UTC
**System Information (please complete the following information):**
 - Model Builder Version: 16.0.1905.641
 - Visual Studio Version: 2017 Community Edition, version 15.9.12

**Describe the bug**
Generated ModelBuilder.cs file does not compile. Below is a copy/paste of the BuildTrainingPipeline method that was generated by Model Builder.

```
        public static IEstimator<ITransformer> BuildTrainingPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations 
            var dataProcessPipeline = mlContext.Transforms.Text.FeaturizeText("SentimentText_tf", "SentimentText")
                                      .Append(mlContext.Transforms.CopyColumns("Features", "SentimentText_tf"))
                                      .Append(mlContext.Transforms.NormalizeMinMax("Features", "Features"))
                                      .AppendCacheCheckpoint(mlContext);

            // Set the training algorithm 
            var trainer = mlContext.BinaryClassification.Trainers.SgdCalibrated(new SgdCalibratedTrainer.Options() { L2Regularization = 1E-05f, ConvergenceTolerance = 0, 001f, NumberOfIterations = 20, Shuffle = false, LabelColumnName = "Sentiment", FeatureColumnName = "Features" });
            var trainingPipeline = dataProcessPipeline.Append(trainer);

            return trainingPipeline;
        }
```

**To Reproduce**
1. Go to 'https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/generate-code'
2. Go through the tutorial

**Expected behavior**
After following the tutorial steps I can build myMLAppML.ConsoleApp project.

**Additional context**
I'm running Model Builder in Windows OS with Finnish language (decimal separator is ','). The problem seems to be that because here in Finland decimal separator is ',' the generated code contains next piece `ConvergenceTolerance = 0, 001f` if I change the decimal separator of the Windows OS to '.' the Model Builder generates `ConvergenceTolerance = 0.0001f` which is correct and I'm able to build the project successfully.

**Comment by tbombach** [comment] 2019-06-11 22:41
Thank you for reporting this! We will fix this and generate code that is appropriate for the OS culture.

**Comment by tbombach** [comment] 2019-06-11 22:41
Duplicate of #93

**Closed by tbombach** 2019-06-11 22:41 UTC
Labels: Customer Reported, P0
