### ISSUE TITLE
Setting SQL DataSource  Login Problem

### ISSUE THREAD

**Issue by mrrcomp** [dotnet/machinelearning-modelbuilder#1540] opened 2021-06-29 04:36 UTC
**System Information (please complete the following information):**
 - Model Builder Version (available in Manage Extensions dialog):  Version:16.6.1.2131904
 - Visual Studio Version :16.10.2

**Describe the bug**
- On which step of the process did you run into an issue: After Defining The SQL Connection Properties Did a Test Connection all was fine 
- Clear description of the problem: on ok of Connection Properties got Login Failed

**To Reproduce**
1. Go to '...' Picked Scenario

**Expected behavior**

**Screenshots**
![ML_ConnectionDef](https://user-images.githubusercontent.com/710257/123740774-a4c33680-d8b1-11eb-9e32-b55022db6efa.png)
![ML_ConnectionDef2](https://user-images.githubusercontent.com/710257/123740777-a55bcd00-d8b1-11eb-95cf-e8f7fb921544.png)
[ML_Conection_log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6730816/ML_Conection_log.txt)

**Additional context**

**Comment by mrrcomp** [comment] 2021-06-29 05:01
Model Builder Version:16.6.1.2131904
Visual Studio 2019 : 16.10.2

After Defining the SQL Connection Properties for the  DataSource and testing that the connection works

![ML_ConnectionDef](https://user-images.githubusercontent.com/710257/123739494-69c00380-d8af-11eb-8ab1-4071f3d9eef1.png)

  returning to select table I get "Login Failed: " 
![ML_ConnectionDef2](https://user-images.githubusercontent.com/710257/123739490-688ed680-d8af-11eb-95ce-0bf51c0ec49f.png)

Here is the log file

[ML_Conection_log.txt](https://github.com/dotnet/machinelearning-modelbuilder/files/6730738/ML_Conection_log.txt)

I tried this with 2 different Servers same results 

Looking forward to a swift solution

Regards

Meir

**Comment by sigal1113** [comment] 2021-07-01 06:47
I got the same problem, and I found if I connect to MS SQL 12.0.5207.0 it happens, 
However if I connect to another SQL with version 13.0.5103.6 it works.

**Comment by ForerunnerG34** [comment] 2021-07-09 17:22
Is there a change of getting a sample .mbconfig file with the SQL connection? Or info about how to manually create one? Maybe the issue in the UI, I'm blocked by this bug.

**Comment by beccamc** [comment] 2021-08-23 18:37
Sorry for the delay on this issue. The root cause is Model Builder trying to use the unencrypted connection string to access the SQL DB. The unencrypted string doesn't save the password, so it's unable to access. I've made the fix to the encrypted string. The fix will ship in September. 

To unblock yourself in the meantime, you can add a password to your SQL connection string. Obviously saving passwords to file is extremely unsecure, and should be treated with extreme caution. 

Try to replace the datasource with the following. Replace _<values>_ with your server, user name, password, and db name 

  "DataSource": {
    "Type": "SQL",
    "ConnectionString": "Data Source=_<COMP\\SQLEXPRESS>_;Initial Catalog=SQLAuth;User ID=_<user123>_;Password=_<PASSWORD123>_",
    "DatabaseName": "_<SQLDB>_",
  },

**Comment by beccamc** [comment] 2021-08-23 20:24
@vzhuqin I don't think you've tested with this setup before. I added instructions to the [test docs](https://github.com/dotnet/machinelearning-tools/blob/main/docs/tests/Instructions/Pre-Requisites/SQLPassword.md). Ping me if you run into problems!

**Comment by vzhuqin** [comment] 2021-08-24 09:09
Hi @beccamc, is this issue not fixed on latest main build: 16.7.2.2142301? I can repro it according to the instructions in test docs.
![1540 repro.gif](https://images.zenhubusercontent.com/60653e492390a08ea616cb10/a3a0fa53-af90-464e-9dcc-c7c1aa13668a)

**Closed** 2021-09-20 16:10 UTC
Labels: Priority:0, Customer Reported
