### ISSUE TITLE
Custom scenario - no options for ML Task

### ISSUE THREAD

**Issue by briacht** [dotnet/machinelearning-modelbuilder#381] opened 2019-11-22 23:02 UTC
I selected Custom Scenario is Scenario screen, and in the Train screen, the drop down for task didn't have any options:
![image](https://user-images.githubusercontent.com/10437687/69466480-3374e680-0d52-11ea-91db-a29b0ae900e8.png)

**Comment by beccamc** [comment] 2019-12-17 01:59
This is a duplicate of #373

**Closed** 2019-12-17 01:59 UTC
Labels: Pre-Release Bug Bash
